(in-package :sb-andor2-win-internal)
(defparameter *andor2-lib* 
  #+win64 (load-shared-object "atmcd64d.dll")
  #+linux (load-shared-object "/usr/local/lib/libandor.so.2.91.30001.0"))
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_GLOBALENABLE 1)
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_CHANNELENABLE 1)
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_FREERUN 2)
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_DISABLEONFRAME 4)
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_RESTARTONFIRE 8)
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_INVERT 16)
(DEFCONSTANT AT_DDGLITE_CONTROLBIT_ENABLEONFIRE 32)
(DEFCONSTANT AT_DDG_POLARITY_POSITIVE 0)
(DEFCONSTANT AT_DDG_POLARITY_NEGATIVE 1)
(DEFCONSTANT AT_DDG_TERMINATION_50OHMS 0)
(DEFCONSTANT AT_DDG_TERMINATION_HIGHZ 1)
(DEFCONSTANT AT_STEPMODE_CONSTANT 0)
(DEFCONSTANT AT_STEPMODE_EXPONENTIAL 1)
(DEFCONSTANT AT_STEPMODE_LOGARITHMIC 2)
(DEFCONSTANT AT_STEPMODE_LINEAR 3)
(DEFCONSTANT AT_STEPMODE_OFF 100)
(DEFCONSTANT AT_GATEMODE_FIRE_AND_GATE 0)
(DEFCONSTANT AT_GATEMODE_FIRE_ONLY 1)
(DEFCONSTANT AT_GATEMODE_GATE_ONLY 2)
(DEFCONSTANT AT_GATEMODE_CW_ON 3)
(DEFCONSTANT AT_GATEMODE_CW_OFF 4)
(DEFCONSTANT AT_GATEMODE_DDG 5)
(DEFCONSTANT DRV_ERROR_CODES 20001)
(DEFCONSTANT DRV_SUCCESS 20002)
(DEFCONSTANT DRV_VXDNOTINSTALLED 20003)
(DEFCONSTANT DRV_ERROR_SCAN 20004)
(DEFCONSTANT DRV_ERROR_CHECK_SUM 20005)
(DEFCONSTANT DRV_ERROR_FILELOAD 20006)
(DEFCONSTANT DRV_UNKNOWN_FUNCTION 20007)
(DEFCONSTANT DRV_ERROR_VXD_INIT 20008)
(DEFCONSTANT DRV_ERROR_ADDRESS 20009)
(DEFCONSTANT DRV_ERROR_PAGELOCK 20010)
(DEFCONSTANT DRV_ERROR_PAGEUNLOCK 20011)
(DEFCONSTANT DRV_ERROR_BOARDTEST 20012)
(DEFCONSTANT DRV_ERROR_ACK 20013)
(DEFCONSTANT DRV_ERROR_UP_FIFO 20014)
(DEFCONSTANT DRV_ERROR_PATTERN 20015)
(DEFCONSTANT DRV_ACQUISITION_ERRORS 20017)
(DEFCONSTANT DRV_ACQ_BUFFER 20018)
(DEFCONSTANT DRV_ACQ_DOWNFIFO_FULL 20019)
(DEFCONSTANT DRV_PROC_UNKONWN_INSTRUCTION 20020)
(DEFCONSTANT DRV_ILLEGAL_OP_CODE 20021)
(DEFCONSTANT DRV_KINETIC_TIME_NOT_MET 20022)
(DEFCONSTANT DRV_ACCUM_TIME_NOT_MET 20023)
(DEFCONSTANT DRV_NO_NEW_DATA 20024)
(DEFCONSTANT DRV_PCI_DMA_FAIL 20025)
(DEFCONSTANT DRV_SPOOLERROR 20026)
(DEFCONSTANT DRV_SPOOLSETUPERROR 20027)
(DEFCONSTANT DRV_FILESIZELIMITERROR 20028)
(DEFCONSTANT DRV_ERROR_FILESAVE 20029)
(DEFCONSTANT DRV_TEMPERATURE_CODES 20033)
(DEFCONSTANT DRV_TEMPERATURE_OFF 20034)
(DEFCONSTANT DRV_TEMPERATURE_NOT_STABILIZED 20035)
(DEFCONSTANT DRV_TEMPERATURE_STABILIZED 20036)
(DEFCONSTANT DRV_TEMPERATURE_NOT_REACHED 20037)
(DEFCONSTANT DRV_TEMPERATURE_OUT_RANGE 20038)
(DEFCONSTANT DRV_TEMPERATURE_NOT_SUPPORTED 20039)
(DEFCONSTANT DRV_TEMPERATURE_DRIFT 20040)
(DEFCONSTANT DRV_TEMP_CODES 20033)
(DEFCONSTANT DRV_TEMP_OFF 20034)
(DEFCONSTANT DRV_TEMP_NOT_STABILIZED 20035)
(DEFCONSTANT DRV_TEMP_STABILIZED 20036)
(DEFCONSTANT DRV_TEMP_NOT_REACHED 20037)
(DEFCONSTANT DRV_TEMP_OUT_RANGE 20038)
(DEFCONSTANT DRV_TEMP_NOT_SUPPORTED 20039)
(DEFCONSTANT DRV_TEMP_DRIFT 20040)
(DEFCONSTANT DRV_GENERAL_ERRORS 20049)
(DEFCONSTANT DRV_INVALID_AUX 20050)
(DEFCONSTANT DRV_COF_NOTLOADED 20051)
(DEFCONSTANT DRV_FPGAPROG 20052)
(DEFCONSTANT DRV_FLEXERROR 20053)
(DEFCONSTANT DRV_GPIBERROR 20054)
(DEFCONSTANT DRV_EEPROMVERSIONERROR 20055)
(DEFCONSTANT DRV_DATATYPE 20064)
(DEFCONSTANT DRV_DRIVER_ERRORS 20065)
(DEFCONSTANT DRV_P1INVALID 20066)
(DEFCONSTANT DRV_P2INVALID 20067)
(DEFCONSTANT DRV_P3INVALID 20068)
(DEFCONSTANT DRV_P4INVALID 20069)
(DEFCONSTANT DRV_INIERROR 20070)
(DEFCONSTANT DRV_COFERROR 20071)
(DEFCONSTANT DRV_ACQUIRING 20072)
(DEFCONSTANT DRV_IDLE 20073)
(DEFCONSTANT DRV_TEMPCYCLE 20074)
(DEFCONSTANT DRV_NOT_INITIALIZED 20075)
(DEFCONSTANT DRV_P5INVALID 20076)
(DEFCONSTANT DRV_P6INVALID 20077)
(DEFCONSTANT DRV_INVALID_MODE 20078)
(DEFCONSTANT DRV_INVALID_FILTER 20079)
(DEFCONSTANT DRV_I2CERRORS 20080)
(DEFCONSTANT DRV_I2CDEVNOTFOUND 20081)
(DEFCONSTANT DRV_I2CTIMEOUT 20082)
(DEFCONSTANT DRV_P7INVALID 20083)
(DEFCONSTANT DRV_P8INVALID 20084)
(DEFCONSTANT DRV_P9INVALID 20085)
(DEFCONSTANT DRV_P10INVALID 20086)
(DEFCONSTANT DRV_P11INVALID 20087)
(DEFCONSTANT DRV_USBERROR 20089)
(DEFCONSTANT DRV_IOCERROR 20090)
(DEFCONSTANT DRV_VRMVERSIONERROR 20091)
(DEFCONSTANT DRV_USB_INTERRUPT_ENDPOINT_ERROR 20093)
(DEFCONSTANT DRV_RANDOM_TRACK_ERROR 20094)
(DEFCONSTANT DRV_INVALID_TRIGGER_MODE 20095)
(DEFCONSTANT DRV_LOAD_FIRMWARE_ERROR 20096)
(DEFCONSTANT DRV_DIVIDE_BY_ZERO_ERROR 20097)
(DEFCONSTANT DRV_INVALID_RINGEXPOSURES 20098)
(DEFCONSTANT DRV_BINNING_ERROR 20099)
(DEFCONSTANT DRV_INVALID_AMPLIFIER 20100)
(DEFCONSTANT DRV_INVALID_COUNTCONVERT_MODE 20101)
(DEFCONSTANT DRV_ERROR_NOCAMERA 20990)
(DEFCONSTANT DRV_NOT_SUPPORTED 20991)
(DEFCONSTANT DRV_NOT_AVAILABLE 20992)
(DEFCONSTANT DRV_ERROR_MAP 20115)
(DEFCONSTANT DRV_ERROR_UNMAP 20116)
(DEFCONSTANT DRV_ERROR_MDL 20117)
(DEFCONSTANT DRV_ERROR_UNMDL 20118)
(DEFCONSTANT DRV_ERROR_BUFFSIZE 20119)
(DEFCONSTANT DRV_ERROR_NOHANDLE 20121)
(DEFCONSTANT DRV_GATING_NOT_AVAILABLE 20130)
(DEFCONSTANT DRV_FPGA_VOLTAGE_ERROR 20131)
(DEFCONSTANT DRV_OW_CMD_FAIL 20150)
(DEFCONSTANT DRV_OWMEMORY_BAD_ADDR 20151)
(DEFCONSTANT DRV_OWCMD_NOT_AVAILABLE 20152)
(DEFCONSTANT DRV_OW_NO_SLAVES 20153)
(DEFCONSTANT DRV_OW_NOT_INITIALIZED 20154)
(DEFCONSTANT DRV_OW_ERROR_SLAVE_NUM 20155)
(DEFCONSTANT DRV_MSTIMINGS_ERROR 20156)
(DEFCONSTANT DRV_OA_NULL_ERROR 20173)
(DEFCONSTANT DRV_OA_PARSE_DTD_ERROR 20174)
(DEFCONSTANT DRV_OA_DTD_VALIDATE_ERROR 20175)
(DEFCONSTANT DRV_OA_FILE_ACCESS_ERROR 20176)
(DEFCONSTANT DRV_OA_FILE_DOES_NOT_EXIST 20177)
(DEFCONSTANT DRV_OA_XML_INVALID_OR_NOT_FOUND_ERROR 20178)
(DEFCONSTANT DRV_OA_PRESET_FILE_NOT_LOADED 20179)
(DEFCONSTANT DRV_OA_USER_FILE_NOT_LOADED 20180)
(DEFCONSTANT DRV_OA_PRESET_AND_USER_FILE_NOT_LOADED 20181)
(DEFCONSTANT DRV_OA_INVALID_FILE 20182)
(DEFCONSTANT DRV_OA_FILE_HAS_BEEN_MODIFIED 20183)
(DEFCONSTANT DRV_OA_BUFFER_FULL 20184)
(DEFCONSTANT DRV_OA_INVALID_STRING_LENGTH 20185)
(DEFCONSTANT DRV_OA_INVALID_CHARS_IN_NAME 20186)
(DEFCONSTANT DRV_OA_INVALID_NAMING 20187)
(DEFCONSTANT DRV_OA_GET_CAMERA_ERROR 20188)
(DEFCONSTANT DRV_OA_MODE_ALREADY_EXISTS 20189)
(DEFCONSTANT DRV_OA_STRINGS_NOT_EQUAL 20190)
(DEFCONSTANT DRV_OA_NO_USER_DATA 20191)
(DEFCONSTANT DRV_OA_VALUE_NOT_SUPPORTED 20192)
(DEFCONSTANT DRV_OA_MODE_DOES_NOT_EXIST 20193)
(DEFCONSTANT DRV_OA_CAMERA_NOT_SUPPORTED 20194)
(DEFCONSTANT DRV_OA_FAILED_TO_GET_MODE 20195)
(DEFCONSTANT DRV_PROCESSING_FAILED 20211)
(DEFCONSTANT AC_ACQMODE_SINGLE 1)
(DEFCONSTANT AC_ACQMODE_VIDEO 2)
(DEFCONSTANT AC_ACQMODE_ACCUMULATE 4)
(DEFCONSTANT AC_ACQMODE_KINETIC 8)
(DEFCONSTANT AC_ACQMODE_FRAMETRANSFER 16)
(DEFCONSTANT AC_ACQMODE_FASTKINETICS 32)
(DEFCONSTANT AC_ACQMODE_OVERLAP 64)
(DEFCONSTANT AC_READMODE_FULLIMAGE 1)
(DEFCONSTANT AC_READMODE_SUBIMAGE 2)
(DEFCONSTANT AC_READMODE_SINGLETRACK 4)
(DEFCONSTANT AC_READMODE_FVB 8)
(DEFCONSTANT AC_READMODE_MULTITRACK 16)
(DEFCONSTANT AC_READMODE_RANDOMTRACK 32)
(DEFCONSTANT AC_READMODE_MULTITRACKSCAN 64)
(DEFCONSTANT AC_TRIGGERMODE_INTERNAL 1)
(DEFCONSTANT AC_TRIGGERMODE_EXTERNAL 2)
(DEFCONSTANT AC_TRIGGERMODE_EXTERNAL_FVB_EM 4)
(DEFCONSTANT AC_TRIGGERMODE_CONTINUOUS 8)
(DEFCONSTANT AC_TRIGGERMODE_EXTERNALSTART 16)
(DEFCONSTANT AC_TRIGGERMODE_EXTERNALEXPOSURE 32)
(DEFCONSTANT AC_TRIGGERMODE_INVERTED 64)
(DEFCONSTANT AC_TRIGGERMODE_BULB 32)
(DEFCONSTANT AC_CAMERATYPE_PDA 0)
(DEFCONSTANT AC_CAMERATYPE_IXON 1)
(DEFCONSTANT AC_CAMERATYPE_ICCD 2)
(DEFCONSTANT AC_CAMERATYPE_EMCCD 3)
(DEFCONSTANT AC_CAMERATYPE_CCD 4)
(DEFCONSTANT AC_CAMERATYPE_ISTAR 5)
(DEFCONSTANT AC_CAMERATYPE_VIDEO 6)
(DEFCONSTANT AC_CAMERATYPE_IDUS 7)
(DEFCONSTANT AC_CAMERATYPE_NEWTON 8)
(DEFCONSTANT AC_CAMERATYPE_SURCAM 9)
(DEFCONSTANT AC_CAMERATYPE_USBICCD 10)
(DEFCONSTANT AC_CAMERATYPE_LUCA 11)
(DEFCONSTANT AC_CAMERATYPE_RESERVED 12)
(DEFCONSTANT AC_CAMERATYPE_IKON 13)
(DEFCONSTANT AC_CAMERATYPE_INGAAS 14)
(DEFCONSTANT AC_CAMERATYPE_IVAC 15)
(DEFCONSTANT AC_CAMERATYPE_UNPROGRAMMED 16)
(DEFCONSTANT AC_CAMERATYPE_CLARA 17)
(DEFCONSTANT AC_CAMERATYPE_USBISTAR 18)
(DEFCONSTANT AC_CAMERATYPE_SIMCAM 19)
(DEFCONSTANT AC_CAMERATYPE_SCMOS 20)
(DEFCONSTANT AC_CAMERATYPE_EXTREME 21)
(DEFCONSTANT AC_PIXELMODE_8BIT 1)
(DEFCONSTANT AC_PIXELMODE_14BIT 2)
(DEFCONSTANT AC_PIXELMODE_16BIT 4)
(DEFCONSTANT AC_PIXELMODE_32BIT 8)
(DEFCONSTANT AC_PIXELMODE_MONO 0)
(DEFCONSTANT AC_PIXELMODE_RGB 65536)
(DEFCONSTANT AC_PIXELMODE_CMY 131072)
(DEFCONSTANT AC_SETFUNCTION_VREADOUT 1)
(DEFCONSTANT AC_SETFUNCTION_HREADOUT 2)
(DEFCONSTANT AC_SETFUNCTION_TEMPERATURE 4)
(DEFCONSTANT AC_SETFUNCTION_MCPGAIN 8)
(DEFCONSTANT AC_SETFUNCTION_EMCCDGAIN 16)
(DEFCONSTANT AC_SETFUNCTION_BASELINECLAMP 32)
(DEFCONSTANT AC_SETFUNCTION_VSAMPLITUDE 64)
(DEFCONSTANT AC_SETFUNCTION_HIGHCAPACITY 128)
(DEFCONSTANT AC_SETFUNCTION_BASELINEOFFSET 256)
(DEFCONSTANT AC_SETFUNCTION_PREAMPGAIN 512)
(DEFCONSTANT AC_SETFUNCTION_CROPMODE 1024)
(DEFCONSTANT AC_SETFUNCTION_DMAPARAMETERS 2048)
(DEFCONSTANT AC_SETFUNCTION_HORIZONTALBIN 4096)
(DEFCONSTANT AC_SETFUNCTION_MULTITRACKHRANGE 8192)
(DEFCONSTANT AC_SETFUNCTION_RANDOMTRACKNOGAPS 16384)
(DEFCONSTANT AC_SETFUNCTION_EMADVANCED 32768)
(DEFCONSTANT AC_SETFUNCTION_GATEMODE 65536)
(DEFCONSTANT AC_SETFUNCTION_DDGTIMES 131072)
(DEFCONSTANT AC_SETFUNCTION_IOC 262144)
(DEFCONSTANT AC_SETFUNCTION_INTELLIGATE 524288)
(DEFCONSTANT AC_SETFUNCTION_INSERTION_DELAY 1048576)
(DEFCONSTANT AC_SETFUNCTION_GATESTEP 2097152)
(DEFCONSTANT AC_SETFUNCTION_TRIGGERTERMINATION 4194304)
(DEFCONSTANT AC_SETFUNCTION_GAIN 8)
(DEFCONSTANT AC_SETFUNCTION_ICCDGAIN 8)
(DEFCONSTANT AC_GETFUNCTION_TEMPERATURE 1)
(DEFCONSTANT AC_GETFUNCTION_TARGETTEMPERATURE 2)
(DEFCONSTANT AC_GETFUNCTION_TEMPERATURERANGE 4)
(DEFCONSTANT AC_GETFUNCTION_DETECTORSIZE 8)
(DEFCONSTANT AC_GETFUNCTION_MCPGAIN 16)
(DEFCONSTANT AC_GETFUNCTION_EMCCDGAIN 32)
(DEFCONSTANT AC_GETFUNCTION_HVFLAG 64)
(DEFCONSTANT AC_GETFUNCTION_GATEMODE 128)
(DEFCONSTANT AC_GETFUNCTION_DDGTIMES 256)
(DEFCONSTANT AC_GETFUNCTION_IOC 512)
(DEFCONSTANT AC_GETFUNCTION_INTELLIGATE 1024)
(DEFCONSTANT AC_GETFUNCTION_INSERTION_DELAY 2048)
(DEFCONSTANT AC_GETFUNCTION_GATESTEP 4096)
(DEFCONSTANT AC_GETFUNCTION_PHOSPHORSTATUS 8192)
(DEFCONSTANT AC_GETFUNCTION_MCPGAINTABLE 16384)
(DEFCONSTANT AC_GETFUNCTION_BASELINECLAMP 32768)
(DEFCONSTANT AC_GETFUNCTION_GAIN 16)
(DEFCONSTANT AC_GETFUNCTION_ICCDGAIN 16)
(DEFCONSTANT AC_FEATURES_POLLING 1)
(DEFCONSTANT AC_FEATURES_EVENTS 2)
(DEFCONSTANT AC_FEATURES_SPOOLING 4)
(DEFCONSTANT AC_FEATURES_SHUTTER 8)
(DEFCONSTANT AC_FEATURES_SHUTTEREX 16)
(DEFCONSTANT AC_FEATURES_EXTERNAL_I2C 32)
(DEFCONSTANT AC_FEATURES_SATURATIONEVENT 64)
(DEFCONSTANT AC_FEATURES_FANCONTROL 128)
(DEFCONSTANT AC_FEATURES_MIDFANCONTROL 256)
(DEFCONSTANT AC_FEATURES_TEMPERATUREDURINGACQUISITION 512)
(DEFCONSTANT AC_FEATURES_KEEPCLEANCONTROL 1024)
(DEFCONSTANT AC_FEATURES_DDGLITE 2048)
(DEFCONSTANT AC_FEATURES_FTEXTERNALEXPOSURE 4096)
(DEFCONSTANT AC_FEATURES_KINETICEXTERNALEXPOSURE 8192)
(DEFCONSTANT AC_FEATURES_DACCONTROL 16384)
(DEFCONSTANT AC_FEATURES_METADATA 32768)
(DEFCONSTANT AC_FEATURES_IOCONTROL 65536)
(DEFCONSTANT AC_FEATURES_PHOTONCOUNTING 131072)
(DEFCONSTANT AC_FEATURES_COUNTCONVERT 262144)
(DEFCONSTANT AC_FEATURES_DUALMODE 524288)
(DEFCONSTANT AC_FEATURES_OPTACQUIRE 1048576)
(DEFCONSTANT AC_FEATURES_REALTIMESPURIOUSNOISEFILTER 2097152)
(DEFCONSTANT AC_FEATURES_POSTPROCESSSPURIOUSNOISEFILTER 4194304)
(DEFCONSTANT AC_EMGAIN_8BIT 1)
(DEFCONSTANT AC_EMGAIN_12BIT 2)
(DEFCONSTANT AC_EMGAIN_LINEAR12 4)
(DEFCONSTANT AC_EMGAIN_REAL12 8)
(DEFINE-ALIEN-ROUTINE ("AbortAcquisition" ABORT-ACQUISITION*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("CancelWait" CANCEL-WAIT*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("CoolerOFF" COOLER-OFF*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("CoolerON" COOLER-ON*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("EnableKeepCleans" ENABLE-KEEP-CLEANS*) UNSIGNED-INT
                      (I-MODE INT))
(DEFINE-ALIEN-ROUTINE ("FreeInternalMemory" FREE-INTERNAL-MEMORY*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("GetAcquiredData" GET-ACQUIRED-DATA*) UNSIGNED-INT
                      (ARR (* LONG)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetAcquiredData16" GET-ACQUIRED-DATA16*) UNSIGNED-INT
                      (ARR (* UNSIGNED-SHORT)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetAcquiredFloatData" GET-ACQUIRED-FLOAT-DATA*)
                      UNSIGNED-INT (ARR (* FLOAT)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetAcquisitionProgress" GET-ACQUISITION-PROGRESS*)
                      UNSIGNED-INT (ACC (* LONG)) (SERIES (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetAcquisitionTimings" GET-ACQUISITION-TIMINGS*)
                      UNSIGNED-INT (EXPOSURE (* FLOAT)) (ACCUMULATE (* FLOAT))
                      (KINETIC (* FLOAT)))
(DEFINE-ALIEN-ROUTINE
 ("GetAdjustedRingExposureTimes" GET-ADJUSTED-RING-EXPOSURE-TIMES*)
 UNSIGNED-INT (INUM-TIMES INT) (FPTIMES (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetAllDMAData" GET-ALL-DMA-DATA*) UNSIGNED-INT
                      (ARR (* LONG)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetAmpDesc" GET-AMP-DESC*) UNSIGNED-INT (INDEX INT)
                      (NAME (* CHAR)) (LENGTH INT))
(DEFINE-ALIEN-ROUTINE ("GetAmpMaxSpeed" GET-AMP-MAX-SPEED*) UNSIGNED-INT
                      (INDEX INT) (SPEED (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetAvailableCameras" GET-AVAILABLE-CAMERAS*)
                      UNSIGNED-INT (TOTAL-CAMERAS (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetBackground" GET-BACKGROUND*) UNSIGNED-INT
                      (ARR (* LONG)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetBaselineClamp" GET-BASELINE-CLAMP*) UNSIGNED-INT
                      (STATE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetBitDepth" GET-BIT-DEPTH*) UNSIGNED-INT (CHANNEL INT)
                      (DEPTH (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetCameraEventStatus" GET-CAMERA-EVENT-STATUS*)
                      UNSIGNED-INT (CAM-STATUS (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetCameraHandle" GET-CAMERA-HANDLE*) UNSIGNED-INT
                      (CAMERA-INDEX LONG) (CAMERA-HANDLE (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetCameraInformation" GET-CAMERA-INFORMATION*)
                      UNSIGNED-INT (INDEX INT) (INFORMATION (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetCameraSerialNumber" GET-CAMERA-SERIAL-NUMBER*)
                      UNSIGNED-INT (NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetCapabilities" GET-CAPABILITIES*) UNSIGNED-INT
                      (CAPS (* ANDORCAPS)))
(DEFINE-ALIEN-ROUTINE ("GetControllerCardModel" GET-CONTROLLER-CARD-MODEL*)
                      UNSIGNED-INT (CONTROLLER-CARD-MODEL (* CHAR)))
(DEFINE-ALIEN-ROUTINE
 ("GetCountConvertWavelengthRange" GET-COUNT-CONVERT-WAVELENGTH-RANGE*)
 UNSIGNED-INT (MINVAL (* FLOAT)) (MAXVAL (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetCurrentCamera" GET-CURRENT-CAMERA*) UNSIGNED-INT
                      (CAMERA-HANDLE (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetCYMGShift" GET-CYMG-SHIFT*) UNSIGNED-INT
                      (I-XSHIFT (* INT)) (I-Y-SHIFT (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetDDGExternalOutputEnabled" GET-DDG-EXTERNAL-OUTPUT-ENABLED*) UNSIGNED-INT
 (UI-INDEX UNSIGNED-LONG) (PUI-ENABLED (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE
 ("GetDDGExternalOutputPolarity" GET-DDG-EXTERNAL-OUTPUT-POLARITY*)
 UNSIGNED-INT (UI-INDEX UNSIGNED-LONG) (PUI-POLARITY (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE
 ("GetDDGExternalOutputStepEnabled" GET-DDG-EXTERNAL-OUTPUT-STEP-ENABLED*)
 UNSIGNED-INT (UI-INDEX UNSIGNED-LONG) (PUI-ENABLED (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE
 ("GetDDGExternalOutputTime" GET-DDG-EXTERNAL-OUTPUT-TIME*) UNSIGNED-INT
 (UI-INDEX UNSIGNED-LONG) (PUI-DELAY (* UNSIGNED-LONG-LONG))
 (PUI-WIDTH (* UNSIGNED-LONG-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetDDGGateTime" GET-DDG-GATE-TIME*) UNSIGNED-INT
                      (PUI-DELAY (* UNSIGNED-LONG-LONG))
                      (PUI-WIDTH (* UNSIGNED-LONG-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetDDGInsertionDelay" GET-DDG-INSERTION-DELAY*)
                      UNSIGNED-INT (PI-STATE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIntelligate" GET-DDG-INTELLIGATE*) UNSIGNED-INT
                      (PI-STATE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIOC" GET-DDGIOC*) UNSIGNED-INT (STATE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIOCFrequency" GET-DDGIOC-FREQUENCY*) UNSIGNED-INT
                      (FREQUENCY (* DOUBLE)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIOCNumber" GET-DDGIOC-NUMBER*) UNSIGNED-INT
                      (NUMBER-PULSES (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIOCNumberRequested" GET-DDGIOC-NUMBER-REQUESTED*)
                      UNSIGNED-INT (PULSES (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIOCPeriod" GET-DDGIOC-PERIOD*) UNSIGNED-INT
                      (PERIOD (* UNSIGNED-LONG-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetDDGIOCPulses" GET-DDGIOC-PULSES*) UNSIGNED-INT
                      (PULSES (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetDDGLiteGlobalControlByte" GET-DDG-LITE-GLOBAL-CONTROL-BYTE*) UNSIGNED-INT
 (CONTROL (* UNSIGNED-CHAR)))
(DEFINE-ALIEN-ROUTINE ("GetDDGPulse" GET-DDG-PULSE*) UNSIGNED-INT (WID DOUBLE)
                      (RESOLUTION DOUBLE) (DELAY (* DOUBLE)) (WIDTH (* DOUBLE)))
(DEFINE-ALIEN-ROUTINE ("GetDDGStepCoefficients" GET-DDG-STEP-COEFFICIENTS*)
                      UNSIGNED-INT (MODE UNSIGNED-LONG) (P1 (* DOUBLE))
                      (P2 (* DOUBLE)))
(DEFINE-ALIEN-ROUTINE ("GetDDGStepMode" GET-DDG-STEP-MODE*) UNSIGNED-INT
                      (MODE (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetDetector" GET-DETECTOR*) UNSIGNED-INT
                      (XPIXELS (* INT)) (YPIXELS (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetEMCCDGain" GET-EMCCD-GAIN*) UNSIGNED-INT
                      (GAIN (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetEMGainRange" GET-EM-GAIN-RANGE*) UNSIGNED-INT
                      (LOW (* INT)) (HIGH (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetExternalTriggerTermination" GET-EXTERNAL-TRIGGER-TERMINATION*)
 UNSIGNED-INT (PUI-TERMINATION (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE
 ("GetFastestRecommendedVSSpeed" GET-FASTEST-RECOMMENDED-VS-SPEED*)
 UNSIGNED-INT (INDEX (* INT)) (SPEED (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetFIFOUsage" GET-FIFO-USAGE*) UNSIGNED-INT
                      (FIF-OUSAGE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetFilterMode" GET-FILTER-MODE*) UNSIGNED-INT
                      (MODE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetFKExposureTime" GET-FK-EXPOSURE-TIME*) UNSIGNED-INT
                      (TIME (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetFKVShiftSpeed" GET-FKV-SHIFT-SPEED*) UNSIGNED-INT
                      (INDEX INT) (SPEED (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetFKVShiftSpeedF" GET-FKV-SHIFT-SPEED-F*) UNSIGNED-INT
                      (INDEX INT) (SPEED (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetFrontEndStatus" GET-FRONT-END-STATUS*) UNSIGNED-INT
                      (PI-FLAG (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetGateMode" GET-GATE-MODE*) UNSIGNED-INT
                      (PI-GATEMODE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetHardwareVersion" GET-HARDWARE-VERSION*) UNSIGNED-INT
                      (PCB (* UNSIGNED-INT)) (DECODE (* UNSIGNED-INT))
                      (DUMMY1 (* UNSIGNED-INT)) (DUMMY2 (* UNSIGNED-INT))
                      (CAMERA-FIRMWARE-VERSION (* UNSIGNED-INT))
                      (CAMERA-FIRMWARE-BUILD (* UNSIGNED-INT)))
(DEFINE-ALIEN-ROUTINE ("GetHeadModel" GET-HEAD-MODEL*) UNSIGNED-INT
                      (NAME (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("GetHorizontalSpeed" GET-HORIZONTAL-SPEED*) UNSIGNED-INT
                      (INDEX INT) (SPEED (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetHSSpeed" GET-HS-SPEED*) UNSIGNED-INT (CHANNEL INT)
                      (TYP INT) (INDEX INT) (SPEED (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetHVflag" GET-H-VFLAG*) UNSIGNED-INT (B-FLAG (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetID" GET-ID*) UNSIGNED-INT (DEV-NUM INT) (ID (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetImageFlip" GET-IMAGE-FLIP*) UNSIGNED-INT
                      (I-H-FLIP (* INT)) (I-V-FLIP (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetImageRotate" GET-IMAGE-ROTATE*) UNSIGNED-INT
                      (I-ROTATE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetImages" GET-IMAGES*) UNSIGNED-INT (FIRST LONG)
                      (LAST LONG) (ARR (* LONG)) (SIZE UNSIGNED-LONG)
                      (VALIDFIRST LONG :out) (VALIDLAST LONG :out))
(DEFINE-ALIEN-ROUTINE ("GetImages16" GET-IMAGES16*) UNSIGNED-INT (FIRST LONG)
                      (LAST LONG) (ARR (* UNSIGNED-SHORT)) (SIZE UNSIGNED-LONG)
                      (VALIDFIRST LONG :out) (VALIDLAST LONG :out))
(DEFINE-ALIEN-ROUTINE ("GetImagesPerDMA" GET-IMAGES-PER-DMA*) UNSIGNED-INT
                      (IMAGES (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetIRQ" GET-IRQ*) UNSIGNED-INT (IRQ (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetKeepCleanTime" GET-KEEP-CLEAN-TIME*) UNSIGNED-INT
                      (KEEP-CLEAN-TIME (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetMaximumBinning" GET-MAXIMUM-BINNING*) UNSIGNED-INT
                      (READ-MODE INT) (HORZ-VERT INT) (MAX-BINNING (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetMaximumExposure" GET-MAXIMUM-EXPOSURE*) UNSIGNED-INT
                      (MAX-EXP (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetMCPGain" GET-MCP-GAIN*) UNSIGNED-INT
                      (PI-GAIN (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetMCPGainRange" GET-MCP-GAIN-RANGE*) UNSIGNED-INT
                      (I-LOW (* INT)) (I-HIGH (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetMCPGainTable" GET-MCP-GAIN-TABLE*) UNSIGNED-INT
                      (I-NUM INT) (PI-GAIN (* INT)) (PF-PHOTOEPC (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetMCPVoltage" GET-MCP-VOLTAGE*) UNSIGNED-INT
                      (I-VOLTAGE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetMinimumImageLength" GET-MINIMUM-IMAGE-LENGTH*)
                      UNSIGNED-INT (MIN-IMAGE-LENGTH (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetMinimumNumberInSeries" GET-MINIMUM-NUMBER-IN-SERIES*) UNSIGNED-INT
 (NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetMostRecentColorImage16" GET-MOST-RECENT-COLOR-IMAGE16*) UNSIGNED-INT
 (SIZE UNSIGNED-LONG) (ALGORITHM INT) (RED (* UNSIGNED-SHORT))
 (GREEN (* UNSIGNED-SHORT)) (BLUE (* UNSIGNED-SHORT)))
(DEFINE-ALIEN-ROUTINE ("GetMostRecentImage" GET-MOST-RECENT-IMAGE*)
                      UNSIGNED-INT (ARR (* LONG)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetMostRecentImage16" GET-MOST-RECENT-IMAGE16*)
                      UNSIGNED-INT (ARR (* UNSIGNED-SHORT))
                      (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetMSTimingsEnabled" GET-MS-TIMINGS-ENABLED*)
                      UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("GetNewData" GET-NEW-DATA*) UNSIGNED-INT (ARR (* LONG))
                      (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetNewData16" GET-NEW-DATA16*) UNSIGNED-INT
                      (ARR (* UNSIGNED-SHORT)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetNewData8" GET-NEW-DATA8*) UNSIGNED-INT
                      (ARR (* UNSIGNED-CHAR)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetNewFloatData" GET-NEW-FLOAT-DATA*) UNSIGNED-INT
                      (ARR (* FLOAT)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetNumberADChannels" GET-NUMBER-AD-CHANNELS*)
                      UNSIGNED-INT (CHANNELS (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberAmp" GET-NUMBER-AMP*) UNSIGNED-INT
                      (AMP (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberAvailableImages" GET-NUMBER-AVAILABLE-IMAGES*)
    UNSIGNED-INT (FIRST LONG :out) (LAST LONG :out))
(DEFINE-ALIEN-ROUTINE
 ("GetNumberDDGExternalOutputs" GET-NUMBER-DDG-EXTERNAL-OUTPUTS*) UNSIGNED-INT
 (PUI-COUNT (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetNumberDevices" GET-NUMBER-DEVICES*) UNSIGNED-INT
                      (NUM-DEVS (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberFKVShiftSpeeds" GET-NUMBER-FKV-SHIFT-SPEEDS*)
                      UNSIGNED-INT (NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetNumberHorizontalSpeeds" GET-NUMBER-HORIZONTAL-SPEEDS*) UNSIGNED-INT
 (NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberHSSpeeds" GET-NUMBER-HS-SPEEDS*) UNSIGNED-INT
                      (CHANNEL INT) (TYP INT) (SPEEDS (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberNewImages" GET-NUMBER-NEW-IMAGES*)
                      UNSIGNED-INT (FIRST (* LONG)) (LAST (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetNumberPreAmpGains" GET-NUMBER-PRE-AMP-GAINS*)
                      UNSIGNED-INT (NO-GAINS (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("GetNumberRingExposureTimes" GET-NUMBER-RING-EXPOSURE-TIMES*) UNSIGNED-INT
 (IPNUM-TIMES (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberIO" GET-NUMBER-IO*) UNSIGNED-INT
                      (I-NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberVerticalSpeeds" GET-NUMBER-VERTICAL-SPEEDS*)
                      UNSIGNED-INT (NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberVSAmplitudes" GET-NUMBER-VS-AMPLITUDES*)
                      UNSIGNED-INT (NUMBER (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetNumberVSSpeeds" GET-NUMBER-VS-SPEEDS*) UNSIGNED-INT
                      (SPEEDS (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetOldestImage" GET-OLDEST-IMAGE*) UNSIGNED-INT
                      (ARR (* LONG)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetOldestImage16" GET-OLDEST-IMAGE16*) UNSIGNED-INT
                      (ARR (* UNSIGNED-SHORT)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("GetPhosphorStatus" GET-PHOSPHOR-STATUS*) UNSIGNED-INT
                      (PI-FLAG (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetPhysicalDMAAddress" GET-PHYSICAL-DMA-ADDRESS*)
                      UNSIGNED-INT (ADDRESS1 (* UNSIGNED-LONG))
                      (ADDRESS2 (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetPixelSize" GET-PIXEL-SIZE*) UNSIGNED-INT
                      (X-SIZE (* FLOAT)) (Y-SIZE (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetPreAmpGain" GET-PRE-AMP-GAIN*) UNSIGNED-INT
                      (INDEX INT) (GAIN (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetDualExposureTimes" GET-DUAL-EXPOSURE-TIMES*)
                      UNSIGNED-INT (EXPOSURE1 (* FLOAT)) (EXPOSURE2 (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetQE" GET-QE*) UNSIGNED-INT (SENSOR (* CHAR))
                      (WAVELENGTH FLOAT) (MODE UNSIGNED-INT) (QE (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetReadOutTime" GET-READ-OUT-TIME*) UNSIGNED-INT
                      (READ-OUT-TIME (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetRegisterDump" GET-REGISTER-DUMP*) UNSIGNED-INT
                      (MODE (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetRingExposureRange" GET-RING-EXPOSURE-RANGE*)
                      UNSIGNED-INT (FP-MIN (* FLOAT)) (FP-MAX (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetSensitivity" GET-SENSITIVITY*) UNSIGNED-INT
                      (CHANNEL INT) (HORZ-SHIFT INT) (AMPLIFIER INT) (PA INT)
                      (SENSITIVITY (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetSizeOfCircularBuffer" GET-SIZE-OF-CIRCULAR-BUFFER*)
                      UNSIGNED-INT (INDEX (* LONG)))
(DEFINE-ALIEN-ROUTINE
 ("GetSlotBusDeviceFunction" GET-SLOT-BUS-DEVICE-FUNCTION*) UNSIGNED-INT
 (DWSLOT (* UNSIGNED-LONG)) (DW-BUS (* UNSIGNED-LONG))
 (DW-DEVICE (* UNSIGNED-LONG)) (DW-FUNCTION (* UNSIGNED-LONG)))
(DEFINE-ALIEN-ROUTINE ("GetSoftwareVersion" GET-SOFTWARE-VERSION*) UNSIGNED-INT
                      (EPROM (* UNSIGNED-INT)) (COFFILE (* UNSIGNED-INT))
                      (VXDREV (* UNSIGNED-INT)) (VXDVER (* UNSIGNED-INT))
                      (DLLREV (* UNSIGNED-INT)) (DLLVER (* UNSIGNED-INT)))
(DEFINE-ALIEN-ROUTINE ("GetSpoolProgress" GET-SPOOL-PROGRESS*) UNSIGNED-INT
                      (INDEX (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetStartUpTime" GET-START-UP-TIME*) UNSIGNED-INT
                      (TIME (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GetStatus" GET-STATUS*) UNSIGNED-INT (STATUS INT :out))
(DEFINE-ALIEN-ROUTINE ("GetTECStatus" GET-TEC-STATUS*) UNSIGNED-INT
                      (PI-FLAG (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetTemperature" GET-TEMPERATURE*) UNSIGNED-INT
  (TEMPERATURE INT :out))
(DEFINE-ALIEN-ROUTINE ("GetTemperatureF" GET-TEMPERATURE-F*) UNSIGNED-INT
  (TEMPERATURE FLOAT :out))
(DEFINE-ALIEN-ROUTINE ("GetTemperatureRange" GET-TEMPERATURE-RANGE*)
                      UNSIGNED-INT (MINTEMP (* INT)) (MAXTEMP (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetTemperatureStatus" GET-TEMPERATURE-STATUS*)
                      UNSIGNED-INT (SENSOR-TEMP (* FLOAT))
                      (TARGET-TEMP (* FLOAT)) (AMBIENT-TEMP (* FLOAT))
                      (COOLER-VOLTS (* FLOAT)))
(DEFINE-ALIEN-ROUTINE
 ("GetTotalNumberImagesAcquired" GET-TOTAL-NUMBER-IMAGES-ACQUIRED*)
 UNSIGNED-INT (INDEX (* LONG)))
(DEFINE-ALIEN-ROUTINE ("GetIODirection" GET-IO-DIRECTION*) UNSIGNED-INT
                      (INDEX INT) (I-DIRECTION (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetIOLevel" GET-IO-LEVEL*) UNSIGNED-INT (INDEX INT)
                      (I-LEVEL (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetVerticalSpeed" GET-VERTICAL-SPEED*) UNSIGNED-INT
                      (INDEX INT) (SPEED (* INT)))
(DEFINE-ALIEN-ROUTINE ("GetVSSpeed" GET-VS-SPEED*) UNSIGNED-INT (INDEX INT)
                      (SPEED (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("GPIBReceive" GPIB-RECEIVE*) UNSIGNED-INT (ID INT)
                      (ADDRESS SHORT) (TEXT (* CHAR)) (SIZE INT))
(DEFINE-ALIEN-ROUTINE ("GPIBSend" GPIB-SEND*) UNSIGNED-INT (ID INT)
                      (ADDRESS SHORT) (TEXT (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("I2CBurstRead" I2C-BURST-READ*) UNSIGNED-INT
                      (I2C-ADDRESS UNSIGNED-CHAR) (N-BYTES LONG)
                      (DATA (* UNSIGNED-CHAR)))
(DEFINE-ALIEN-ROUTINE ("I2CBurstWrite" I2C-BURST-WRITE*) UNSIGNED-INT
                      (I2C-ADDRESS UNSIGNED-CHAR) (N-BYTES LONG)
                      (DATA (* UNSIGNED-CHAR)))
(DEFINE-ALIEN-ROUTINE ("I2CRead" I2C-READ*) UNSIGNED-INT
                      (DEVICE-ID UNSIGNED-CHAR) (INT-ADDRESS UNSIGNED-CHAR)
                      (PDATA (* UNSIGNED-CHAR)))
(DEFINE-ALIEN-ROUTINE ("I2CReset" I2C-RESET*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("I2CWrite" I2C-WRITE*) UNSIGNED-INT
                      (DEVICE-ID UNSIGNED-CHAR) (INT-ADDRESS UNSIGNED-CHAR)
                      (DATA UNSIGNED-CHAR))
(DEFINE-ALIEN-ROUTINE ("IdAndorDll" ID-ANDOR-DLL*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("InAuxPort" IN-AUX-PORT*) UNSIGNED-INT (PORT INT)
                      (STATE (* INT)))
(DEFINE-ALIEN-ROUTINE ("Initialize" INITIALIZE*) UNSIGNED-INT (DIR (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("InitializeDevice" INITIALIZE-DEVICE*) UNSIGNED-INT
                      (DIR (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("IsAmplifierAvailable" IS-AMPLIFIER-AVAILABLE*)
                      UNSIGNED-INT (IAMP INT))
(DEFINE-ALIEN-ROUTINE ("IsCoolerOn" IS-COOLER-ON*) UNSIGNED-INT
                      (I-COOLER-STATUS (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("IsCountConvertModeAvailable" IS-COUNT-CONVERT-MODE-AVAILABLE*) UNSIGNED-INT
 (MODE INT))
(DEFINE-ALIEN-ROUTINE
 ("IsInternalMechanicalShutter" IS-INTERNAL-MECHANICAL-SHUTTER*) UNSIGNED-INT
 (INTERNAL-SHUTTER (* INT)))
(DEFINE-ALIEN-ROUTINE ("IsPreAmpGainAvailable" IS-PRE-AMP-GAIN-AVAILABLE*)
                      UNSIGNED-INT (CHANNEL INT) (AMPLIFIER INT) (INDEX INT)
                      (PA INT) (STATUS (* INT)))
(DEFINE-ALIEN-ROUTINE ("IsTriggerModeAvailable" IS-TRIGGER-MODE-AVAILABLE*)
                      UNSIGNED-INT (I-TRIGGER-MODE INT))
(DEFINE-ALIEN-ROUTINE ("OutAuxPort" OUT-AUX-PORT*) UNSIGNED-INT (PORT INT)
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE ("PrepareAcquisition" PREPARE-ACQUISITION*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("SaveAsBmp" SAVE-AS-BMP*) UNSIGNED-INT (PATH (* CHAR))
                      (PALETTE (* CHAR)) (YMIN LONG) (YMAX LONG))
(DEFINE-ALIEN-ROUTINE ("SaveAsCommentedSif" SAVE-AS-COMMENTED-SIF*)
                      UNSIGNED-INT (PATH (* CHAR)) (COMMENT (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("SaveAsEDF" SAVE-AS-EDF*) UNSIGNED-INT
                      (SZ-PATH (* CHAR)) (I-MODE INT))
(DEFINE-ALIEN-ROUTINE ("SaveAsFITS" SAVE-AS-FITS*) UNSIGNED-INT
                      (SZ-FILE-TITLE (* CHAR)) (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SaveAsRaw" SAVE-AS-RAW*) UNSIGNED-INT
                      (SZ-FILE-TITLE (* CHAR)) (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SaveAsSif" SAVE-AS-SIF*) UNSIGNED-INT (PATH (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("SaveAsSPC" SAVE-AS-SPC*) UNSIGNED-INT (PATH (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("SaveAsTiff" SAVE-AS-TIFF*) UNSIGNED-INT (PATH (* CHAR))
                      (PALETTE (* CHAR)) (POSITION INT) (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SaveAsTiffEx" SAVE-AS-TIFF-EX*) UNSIGNED-INT
                      (PATH (* CHAR)) (PALETTE (* CHAR)) (POSITION INT)
                      (TYP INT) (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SaveEEPROMToFile" SAVE-EEPROM-TO-FILE*) UNSIGNED-INT
                      (C-FILE-NAME (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("SaveToClipBoard" SAVE-TO-CLIP-BOARD*) UNSIGNED-INT
                      (PALETTE (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("SelectDevice" SELECT-DEVICE*) UNSIGNED-INT
                      (DEV-NUM INT))
(DEFINE-ALIEN-ROUTINE ("SendSoftwareTrigger" SEND-SOFTWARE-TRIGGER*)
                      UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("SetAccumulationCycleTime" SET-ACCUMULATION-CYCLE-TIME*)
                      UNSIGNED-INT (TIME FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetAcquisitionMode" SET-ACQUISITION-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetAcquisitionType" SET-ACQUISITION-TYPE*) UNSIGNED-INT
                      (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SetADChannel" SET-AD-CHANNEL*) UNSIGNED-INT
                      (CHANNEL INT))
(DEFINE-ALIEN-ROUTINE
 ("SetAdvancedTriggerModeState" SET-ADVANCED-TRIGGER-MODE-STATE*) UNSIGNED-INT
 (I-STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetBackground" SET-BACKGROUND*) UNSIGNED-INT
                      (ARR (* LONG)) (SIZE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("SetBaselineClamp" SET-BASELINE-CLAMP*) UNSIGNED-INT
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetBaselineOffset" SET-BASELINE-OFFSET*) UNSIGNED-INT
                      (OFFSET INT))
(DEFINE-ALIEN-ROUTINE ("SetCameraStatusEnable" SET-CAMERA-STATUS-ENABLE*)
                      UNSIGNED-INT (ENABLE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("SetComplexImage" SET-COMPLEX-IMAGE*) UNSIGNED-INT
                      (NUM-AREAS INT) (AREAS (* INT)))
(DEFINE-ALIEN-ROUTINE ("SetCoolerMode" SET-COOLER-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetCountConvertMode" SET-COUNT-CONVERT-MODE*)
                      UNSIGNED-INT (MODE INT))
(DEFINE-ALIEN-ROUTINE
 ("SetCountConvertWavelength" SET-COUNT-CONVERT-WAVELENGTH*) UNSIGNED-INT
 (WAVELENGTH FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetCropMode" SET-CROP-MODE*) UNSIGNED-INT (ACTIVE INT)
                      (CROP-HEIGHT INT) (RESERVED INT))
(DEFINE-ALIEN-ROUTINE ("SetCurrentCamera" SET-CURRENT-CAMERA*) UNSIGNED-INT
                      (CAMERA-HANDLE LONG))
(DEFINE-ALIEN-ROUTINE ("SetCustomTrackHBin" SET-CUSTOM-TRACK-H-BIN*)
                      UNSIGNED-INT (BIN INT))
(DEFINE-ALIEN-ROUTINE ("SetDataType" SET-DATA-TYPE*) UNSIGNED-INT (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SetDACOutput" SET-DAC-OUTPUT*) UNSIGNED-INT
                      (I-OPTION INT) (I-RESOLUTION INT) (I-VALUE INT))
(DEFINE-ALIEN-ROUTINE ("SetDACOutputScale" SET-DAC-OUTPUT-SCALE*) UNSIGNED-INT
                      (I-SCALE INT))
(DEFINE-ALIEN-ROUTINE ("SetDDGAddress" SET-DDG-ADDRESS*) UNSIGNED-INT
                      (T0 UNSIGNED-CHAR) (T1 UNSIGNED-CHAR) (T2 UNSIGNED-CHAR)
                      (T3 UNSIGNED-CHAR) (ADDRESS UNSIGNED-CHAR))
(DEFINE-ALIEN-ROUTINE
 ("SetDDGExternalOutputEnabled" SET-DDG-EXTERNAL-OUTPUT-ENABLED*) UNSIGNED-INT
 (UI-INDEX UNSIGNED-LONG) (UI-ENABLED UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE
 ("SetDDGExternalOutputPolarity" SET-DDG-EXTERNAL-OUTPUT-POLARITY*)
 UNSIGNED-INT (UI-INDEX UNSIGNED-LONG) (UI-POLARITY UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE
 ("SetDDGExternalOutputStepEnabled" SET-DDG-EXTERNAL-OUTPUT-STEP-ENABLED*)
 UNSIGNED-INT (UI-INDEX UNSIGNED-LONG) (UI-ENABLED UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE
 ("SetDDGExternalOutputTime" SET-DDG-EXTERNAL-OUTPUT-TIME*) UNSIGNED-INT
 (UI-INDEX UNSIGNED-LONG) (UI-DELAY UNSIGNED-LONG-LONG)
 (UI-WIDTH UNSIGNED-LONG-LONG))
(DEFINE-ALIEN-ROUTINE ("SetDDGGain" SET-DDG-GAIN*) UNSIGNED-INT (GAIN INT))
(DEFINE-ALIEN-ROUTINE ("SetDDGGateStep" SET-DDG-GATE-STEP*) UNSIGNED-INT
                      (STEP_RENAMED DOUBLE))
(DEFINE-ALIEN-ROUTINE ("SetDDGGateTime" SET-DDG-GATE-TIME*) UNSIGNED-INT
                      (UI-DELAY UNSIGNED-LONG-LONG)
                      (UI-WIDTH UNSIGNED-LONG-LONG))
(DEFINE-ALIEN-ROUTINE ("SetDDGInsertionDelay" SET-DDG-INSERTION-DELAY*)
                      UNSIGNED-INT (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetDDGIntelligate" SET-DDG-INTELLIGATE*) UNSIGNED-INT
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetDDGIOC" SET-DDGIOC*) UNSIGNED-INT (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetDDGIOCFrequency" SET-DDGIOC-FREQUENCY*) UNSIGNED-INT
                      (FREQUENCY DOUBLE))
(DEFINE-ALIEN-ROUTINE ("SetDDGIOCNumber" SET-DDGIOC-NUMBER*) UNSIGNED-INT
                      (NUMBER-PULSES UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("SetDDGIOCPeriod" SET-DDGIOC-PERIOD*) UNSIGNED-INT
                      (PERIOD UNSIGNED-LONG-LONG))
(DEFINE-ALIEN-ROUTINE
 ("SetDDGLiteGlobalControlByte" SET-DDG-LITE-GLOBAL-CONTROL-BYTE*) UNSIGNED-INT
 (CONTROL UNSIGNED-CHAR))
(DEFINE-ALIEN-ROUTINE ("SetDDGStepCoefficients" SET-DDG-STEP-COEFFICIENTS*)
                      UNSIGNED-INT (MODE UNSIGNED-LONG) (P1 DOUBLE) (P2 DOUBLE))
(DEFINE-ALIEN-ROUTINE ("SetDDGStepMode" SET-DDG-STEP-MODE*) UNSIGNED-INT
                      (MODE UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("SetDDGTimes" SET-DDG-TIMES*) UNSIGNED-INT (T0 DOUBLE)
                      (T1 DOUBLE) (T2 DOUBLE))
(DEFINE-ALIEN-ROUTINE ("SetDDGTriggerMode" SET-DDG-TRIGGER-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetDDGVariableGateStep" SET-DDG-VARIABLE-GATE-STEP*)
                      UNSIGNED-INT (MODE INT) (P1 DOUBLE) (P2 DOUBLE))
(DEFINE-ALIEN-ROUTINE ("SetDelayGenerator" SET-DELAY-GENERATOR*) UNSIGNED-INT
                      (BOARD INT) (ADDRESS SHORT) (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SetDMAParameters" SET-DMA-PARAMETERS*) UNSIGNED-INT
                      (MAX-IMAGES-PER-DMA INT) (SECONDS-PER-DMA FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetEMAdvanced" SET-EM-ADVANCED*) UNSIGNED-INT
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetEMCCDGain" SET-EMCCD-GAIN*) UNSIGNED-INT (GAIN INT))
(DEFINE-ALIEN-ROUTINE ("SetEMClockCompensation" SET-EM-CLOCK-COMPENSATION*)
                      UNSIGNED-INT (EM-CLOCK-COMPENSATION-FLAG INT))
(DEFINE-ALIEN-ROUTINE ("SetEMGainMode" SET-EM-GAIN-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetExposureTime" SET-EXPOSURE-TIME*) UNSIGNED-INT
                      (TIME FLOAT))
(DEFINE-ALIEN-ROUTINE
 ("SetExternalTriggerTermination" SET-EXTERNAL-TRIGGER-TERMINATION*)
 UNSIGNED-INT (UI-TERMINATION UNSIGNED-LONG))
(DEFINE-ALIEN-ROUTINE ("SetFanMode" SET-FAN-MODE*) UNSIGNED-INT (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetFastExtTrigger" SET-FAST-EXT-TRIGGER*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetFastKinetics" SET-FAST-KINETICS*) UNSIGNED-INT
                      (EXPOSED-ROWS INT) (SERIES-LENGTH INT) (TIME FLOAT)
                      (MODE INT) (HBIN INT) (VBIN INT))
(DEFINE-ALIEN-ROUTINE ("SetFastKineticsEx" SET-FAST-KINETICS-EX*) UNSIGNED-INT
                      (EXPOSED-ROWS INT) (SERIES-LENGTH INT) (TIME FLOAT)
                      (MODE INT) (HBIN INT) (VBIN INT) (OFFSET INT))
(DEFINE-ALIEN-ROUTINE ("SetFilterMode" SET-FILTER-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetFilterParameters" SET-FILTER-PARAMETERS*)
                      UNSIGNED-INT (WIDTH INT) (SENSITIVITY FLOAT) (RANGE INT)
                      (ACCEPT FLOAT) (SMOOTH INT) (NOISE INT))
(DEFINE-ALIEN-ROUTINE ("SetFKVShiftSpeed" SET-FKV-SHIFT-SPEED*) UNSIGNED-INT
                      (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("SetFPDP" SET-FPDP*) UNSIGNED-INT (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetFrameTransferMode" SET-FRAME-TRANSFER-MODE*)
                      UNSIGNED-INT (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetFullImage" SET-FULL-IMAGE*) UNSIGNED-INT (HBIN INT)
                      (VBIN INT))
(DEFINE-ALIEN-ROUTINE ("SetFVBHBin" SET-FVBH-BIN*) UNSIGNED-INT (BIN INT))
(DEFINE-ALIEN-ROUTINE ("SetGain" SET-GAIN*) UNSIGNED-INT (GAIN INT))
(DEFINE-ALIEN-ROUTINE ("SetGate" SET-GATE*) UNSIGNED-INT (DELAY FLOAT)
                      (WIDTH FLOAT) (STEP-RENAMED FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetGateMode" SET-GATE-MODE*) UNSIGNED-INT
                      (GATEMODE INT))
(DEFINE-ALIEN-ROUTINE ("SetHighCapacity" SET-HIGH-CAPACITY*) UNSIGNED-INT
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetHorizontalSpeed" SET-HORIZONTAL-SPEED*) UNSIGNED-INT
                      (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("SetHSSpeed" SET-HS-SPEED*) UNSIGNED-INT (TYP INT)
                      (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("SetImage" SET-IMAGE*) UNSIGNED-INT (HBIN INT)
                      (VBIN INT) (HSTART INT) (HEND INT) (VSTART INT)
                      (VEND INT))
(DEFINE-ALIEN-ROUTINE ("SetImageFlip" SET-IMAGE-FLIP*) UNSIGNED-INT
                      (I-H-FLIP INT) (I-V-FLIP INT))
(DEFINE-ALIEN-ROUTINE ("SetImageRotate" SET-IMAGE-ROTATE*) UNSIGNED-INT
                      (I-ROTATE INT))
(DEFINE-ALIEN-ROUTINE ("SetIsolatedCropMode" SET-ISOLATED-CROP-MODE*)
                      UNSIGNED-INT (ACTIVE INT) (CROPHEIGHT INT)
                      (CROPWIDTH INT) (VBIN INT) (HBIN INT))
(DEFINE-ALIEN-ROUTINE ("SetKineticCycleTime" SET-KINETIC-CYCLE-TIME*)
                      UNSIGNED-INT (TIME FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetMCPGain" SET-MCP-GAIN*) UNSIGNED-INT (GAIN INT))
(DEFINE-ALIEN-ROUTINE ("SetMCPGating" SET-MCP-GATING*) UNSIGNED-INT
                      (GATING INT))
(DEFINE-ALIEN-ROUTINE ("SetMetaData" SET-META-DATA*) UNSIGNED-INT (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetMultiTrack" SET-MULTI-TRACK*) UNSIGNED-INT
                      (NUMBER INT) (HEIGHT INT) (OFFSET INT) (BOTTOM (* INT))
                      (GAP (* INT)))
(DEFINE-ALIEN-ROUTINE ("SetMultiTrackHBin" SET-MULTI-TRACK-H-BIN*) UNSIGNED-INT
                      (BIN INT))
(DEFINE-ALIEN-ROUTINE ("SetMultiTrackHRange" SET-MULTI-TRACK-H-RANGE*)
                      UNSIGNED-INT (I-START INT) (I-END INT))
(DEFINE-ALIEN-ROUTINE ("SetMultiTrackScan" SET-MULTI-TRACK-SCAN*) UNSIGNED-INT
                      (TRACK-HEIGHT INT) (NUMBER-TRACKS INT) (I-SIH-START INT)
                      (I-SIH-END INT) (TRACK-H-BINNING INT)
                      (TRACK-V-BINNING INT) (TRACK-GAP INT) (TRACK-OFFSET INT)
                      (TRACK-SKIP INT) (NUMBER-SUB-FRAMES INT))
(DEFINE-ALIEN-ROUTINE ("SetNextAddress" SET-NEXT-ADDRESS*) UNSIGNED-INT
                      (DATA (* LONG)) (LOW-ADD LONG) (HIGH-ADD LONG)
                      (LENGTH LONG) (PHYSICAL LONG))
(DEFINE-ALIEN-ROUTINE ("SetNextAddress16" SET-NEXT-ADDRESS16*) UNSIGNED-INT
                      (DATA (* LONG)) (LOW-ADD LONG) (HIGH-ADD LONG)
                      (LENGTH LONG) (PHYSICAL LONG))
(DEFINE-ALIEN-ROUTINE ("SetNumberAccumulations" SET-NUMBER-ACCUMULATIONS*)
                      UNSIGNED-INT (NUMBER INT))
(DEFINE-ALIEN-ROUTINE ("SetNumberKinetics" SET-NUMBER-KINETICS*) UNSIGNED-INT
                      (NUMBER INT))
(DEFINE-ALIEN-ROUTINE ("SetNumberPrescans" SET-NUMBER-PRESCANS*) UNSIGNED-INT
                      (I-NUMBER INT))
(DEFINE-ALIEN-ROUTINE ("SetOutputAmplifier" SET-OUTPUT-AMPLIFIER*) UNSIGNED-INT
                      (TYP INT))
(DEFINE-ALIEN-ROUTINE ("SetOverlapMode" SET-OVERLAP-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetPCIMode" SET-PCI-MODE*) UNSIGNED-INT (MODE INT)
                      (VALUE INT))
(DEFINE-ALIEN-ROUTINE ("SetPhotonCounting" SET-PHOTON-COUNTING*) UNSIGNED-INT
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE
 ("SetPhotonCountingThreshold" SET-PHOTON-COUNTING-THRESHOLD*) UNSIGNED-INT
 (MIN LONG) (MAX LONG))
(DEFINE-ALIEN-ROUTINE
 ("SetPhotonCountingDivisions" SET-PHOTON-COUNTING-DIVISIONS*) UNSIGNED-INT
 (NO-OF-DIVISIONS UNSIGNED-LONG) (DIVISIONS (* LONG)))
(DEFINE-ALIEN-ROUTINE ("SetPixelMode" SET-PIXEL-MODE*) UNSIGNED-INT
                      (BITDEPTH INT) (COLORMODE INT))
(DEFINE-ALIEN-ROUTINE ("SetPreAmpGain" SET-PRE-AMP-GAIN*) UNSIGNED-INT
                      (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("SetDualExposureTimes" SET-DUAL-EXPOSURE-TIMES*)
                      UNSIGNED-INT (EXP-TIME1 FLOAT) (EXP-TIME2 FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetDualExposureMode" SET-DUAL-EXPOSURE-MODE*)
                      UNSIGNED-INT (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetRandomTracks" SET-RANDOM-TRACKS*) UNSIGNED-INT
                      (NUM-TRACKS INT) (AREAS (* INT)))
(DEFINE-ALIEN-ROUTINE ("SetReadMode" SET-READ-MODE*) UNSIGNED-INT (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetRegisterDump" SET-REGISTER-DUMP*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetRingExposureTimes" SET-RING-EXPOSURE-TIMES*)
                      UNSIGNED-INT (NUM-TIMES INT) (TIMES (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("SetShutter" SET-SHUTTER*) UNSIGNED-INT (TYP INT)
                      (MODE INT) (CLOSINGTIME INT) (OPENINGTIME INT))
(DEFINE-ALIEN-ROUTINE ("SetShutterEx" SET-SHUTTER-EX*) UNSIGNED-INT (TYP INT)
                      (MODE INT) (CLOSINGTIME INT) (OPENINGTIME INT)
                      (EXTMODE INT))
(DEFINE-ALIEN-ROUTINE ("SetShutters" SET-SHUTTERS*) UNSIGNED-INT (TYP INT)
                      (MODE INT) (CLOSINGTIME INT) (OPENINGTIME INT)
                      (EXTTYPE INT) (EXTMODE INT) (DUMMY1 INT) (DUMMY2 INT))
(DEFINE-ALIEN-ROUTINE ("SetSifComment" SET-SIF-COMMENT*) UNSIGNED-INT
                      (COMMENT (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("SetSingleTrack" SET-SINGLE-TRACK*) UNSIGNED-INT
                      (CENTRE INT) (HEIGHT INT))
(DEFINE-ALIEN-ROUTINE ("SetSingleTrackHBin" SET-SINGLE-TRACK-H-BIN*)
                      UNSIGNED-INT (BIN INT))
(DEFINE-ALIEN-ROUTINE ("SetSpool" SET-SPOOL*) UNSIGNED-INT (ACTIVE INT)
                      (METHOD INT) (PATH (* CHAR)) (FRAMEBUFFERSIZE INT))
(DEFINE-ALIEN-ROUTINE ("SetStorageMode" SET-STORAGE-MODE*) UNSIGNED-INT
                      (MODE LONG))
(DEFINE-ALIEN-ROUTINE ("SetTemperature" SET-TEMPERATURE*) UNSIGNED-INT
                      (TEMPERATURE INT))
(DEFINE-ALIEN-ROUTINE ("SetTriggerMode" SET-TRIGGER-MODE*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("SetTriggerInvert" SET-TRIGGER-INVERT*) UNSIGNED-INT
                      (MODE INT))
(DEFINE-ALIEN-ROUTINE ("GetTriggerLevelRange" GET-TRIGGER-LEVEL-RANGE*)
                      UNSIGNED-INT (MINIMUM (* FLOAT)) (MAXIMUM (* FLOAT)))
(DEFINE-ALIEN-ROUTINE ("SetTriggerLevel" SET-TRIGGER-LEVEL*) UNSIGNED-INT
                      (F_LEVEL FLOAT))
(DEFINE-ALIEN-ROUTINE ("SetIODirection" SET-IO-DIRECTION*) UNSIGNED-INT
                      (INDEX INT) (I-DIRECTION INT))
(DEFINE-ALIEN-ROUTINE ("SetIOLevel" SET-IO-LEVEL*) UNSIGNED-INT (INDEX INT)
                      (I-LEVEL INT))
(DEFINE-ALIEN-ROUTINE ("SetUSGenomics" SET-US-GENOMICS*) UNSIGNED-INT
                      (WIDTH LONG) (HEIGHT LONG))
(DEFINE-ALIEN-ROUTINE ("SetVerticalRowBuffer" SET-VERTICAL-ROW-BUFFER*)
                      UNSIGNED-INT (ROWS INT))
(DEFINE-ALIEN-ROUTINE ("SetVerticalSpeed" SET-VERTICAL-SPEED*) UNSIGNED-INT
                      (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("SetVirtualChip" SET-VIRTUAL-CHIP*) UNSIGNED-INT
                      (STATE INT))
(DEFINE-ALIEN-ROUTINE ("SetVSAmplitude" SET-VS-AMPLITUDE*) UNSIGNED-INT
                      (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("SetVSSpeed" SET-VS-SPEED*) UNSIGNED-INT (INDEX INT))
(DEFINE-ALIEN-ROUTINE ("ShutDown" SHUT-DOWN*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("StartAcquisition" START-ACQUISITION*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("UnMapPhysicalAddress" UN-MAP-PHYSICAL-ADDRESS*)
                      UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE ("WaitForAcquisition" WAIT-FOR-ACQUISITION*) UNSIGNED-INT)
(DEFINE-ALIEN-ROUTINE
 ("WaitForAcquisitionByHandle" WAIT-FOR-ACQUISITION-BY-HANDLE*) UNSIGNED-INT
 (CAMERA-HANDLE LONG))
(DEFINE-ALIEN-ROUTINE
 ("WaitForAcquisitionByHandleTimeOut" WAIT-FOR-ACQUISITION-BY-HANDLE-TIME-OUT*)
 UNSIGNED-INT (CAMERA-HANDLE LONG) (I-TIME-OUT-MS INT))
(DEFINE-ALIEN-ROUTINE
 ("WaitForAcquisitionTimeOut" WAIT-FOR-ACQUISITION-TIME-OUT*) UNSIGNED-INT
 (I-TIME-OUT-MS INT))
(DEFINE-ALIEN-ROUTINE ("OA_GetUserModeNames" OA_GET-USER-MODE-NAMES*)
                      UNSIGNED-INT (PC-LIST-OF-MODES (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("OA_GetPreSetModeNames" OA_GET-PRE-SET-MODE-NAMES*)
                      UNSIGNED-INT (PC-LIST-OF-MODES (* CHAR)))
(DEFINE-ALIEN-ROUTINE ("OA_AddMode" OA_ADD-MODE*) UNSIGNED-INT
                      (PC-MODE-NAME (* CHAR)) (UI-MODE-NAME-LEN UNSIGNED-INT)
                      (PC-MODE-DESCRIPTION (* CHAR))
                      (UI-MODE-DESCRIPTION-LEN UNSIGNED-INT))
(DEFINE-ALIEN-ROUTINE ("Filter_SetMode" FILTER_SET-MODE*) UNSIGNED-INT
                      (MODE UNSIGNED-INT))
(DEFINE-ALIEN-ROUTINE ("Filter_GetMode" FILTER_GET-MODE*) UNSIGNED-INT
                      (MODE (* UNSIGNED-INT)))
(DEFINE-ALIEN-ROUTINE ("Filter_SetThreshold" FILTER_SET-THRESHOLD*)
                      UNSIGNED-INT (THRESHOLD FLOAT))
(DEFINE-ALIEN-ROUTINE ("Filter_GetThreshold" FILTER_GET-THRESHOLD*)
                      UNSIGNED-INT (THRESHOLD (* FLOAT)))
(DEFINE-ALIEN-ROUTINE
 ("Filter_SetDataAveragingMode" FILTER_SET-DATA-AVERAGING-MODE*) UNSIGNED-INT
 (MODE INT))
(DEFINE-ALIEN-ROUTINE
 ("Filter_GetDataAveragingMode" FILTER_GET-DATA-AVERAGING-MODE*) UNSIGNED-INT
 (MODE (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("Filter_SetAveragingFrameCount" FILTER_SET-AVERAGING-FRAME-COUNT*)
 UNSIGNED-INT (FRAMES INT))
(DEFINE-ALIEN-ROUTINE
 ("Filter_GetAveragingFrameCount" FILTER_GET-AVERAGING-FRAME-COUNT*)
 UNSIGNED-INT (FRAMES (* INT)))
(DEFINE-ALIEN-ROUTINE
 ("Filter_SetAveragingFactor" FILTER_SET-AVERAGING-FACTOR*) UNSIGNED-INT
 (AVERAGING-FACTOR INT))
(DEFINE-ALIEN-ROUTINE
 ("Filter_GetAveragingFactor" FILTER_GET-AVERAGING-FACTOR*) UNSIGNED-INT
 (AVERAGING-FACTOR (* INT)))
(DEFINE-ALIEN-ROUTINE ("PostProcessNoiseFilter" POST-PROCESS-NOISE-FILTER*)
                      UNSIGNED-INT (P-INPUT-IMAGE (* LONG))
                      (P-OUTPUT-IMAGE (* LONG)) (I-OUTPUT-BUFFER-SIZE INT)
                      (I-BASELINE INT) (I-MODE INT) (F-THRESHOLD FLOAT)
                      (I-HEIGHT INT) (I-WIDTH INT))
(DEFINE-ALIEN-ROUTINE ("PostProcessCountConvert" POST-PROCESS-COUNT-CONVERT*)
                      UNSIGNED-INT (P-INPUT-IMAGE (* LONG))
                      (P-OUTPUT-IMAGE (* LONG)) (I-OUTPUT-BUFFER-SIZE INT)
                      (I-NUM-IMAGES INT) (I-BASELINE INT) (I-MODE INT)
                      (I-EM-GAIN INT) (F-QE FLOAT) (F-SENSITIVITY FLOAT)
                      (I-HEIGHT INT) (I-WIDTH INT))
(DEFINE-ALIEN-ROUTINE
 ("PostProcessPhotonCounting" POST-PROCESS-PHOTON-COUNTING*) UNSIGNED-INT
 (P-INPUT-IMAGE (* LONG)) (P-OUTPUT-IMAGE (* LONG)) (I-OUTPUT-BUFFER-SIZE INT)
 (I-NUM-IMAGES INT) (I-NUMFRAMES INT) (I-NUMBER-OF-THRESHOLDS INT)
 (PF-THRESHOLD (* FLOAT)) (I-HEIGHT INT) (I-WIDTH INT))
(DEFINE-ALIEN-ROUTINE ("PostProcessDataAveraging" POST-PROCESS-DATA-AVERAGING*)
                      UNSIGNED-INT (P-INPUT-IMAGE (* LONG))
                      (P-OUTPUT-IMAGE (* LONG)) (I-OUTPUT-BUFFER-SIZE INT)
                      (I-NUM-IMAGES INT) (I-AVERAGING-FILTER-MODE INT)
                      (I-HEIGHT INT) (I-WIDTH INT) (I-FRAME-COUNT INT)
                      (I-AVERAGING-FACTOR INT))
(PROGN
 (DEFPARAMETER *DRV-HASH* (MAKE-HASH-TABLE))
 (DOLIST
     (E
      '((DRV_ERROR_CODES 20001) (DRV_SUCCESS 20002) (DRV_VXDNOTINSTALLED 20003)
        (DRV_ERROR_SCAN 20004) (DRV_ERROR_CHECK_SUM 20005)
        (DRV_ERROR_FILELOAD 20006) (DRV_UNKNOWN_FUNCTION 20007)
        (DRV_ERROR_VXD_INIT 20008) (DRV_ERROR_ADDRESS 20009)
        (DRV_ERROR_PAGELOCK 20010) (DRV_ERROR_PAGEUNLOCK 20011)
        (DRV_ERROR_BOARDTEST 20012) (DRV_ERROR_ACK 20013)
        (DRV_ERROR_UP_FIFO 20014) (DRV_ERROR_PATTERN 20015)
        (DRV_ACQUISITION_ERRORS 20017) (DRV_ACQ_BUFFER 20018)
        (DRV_ACQ_DOWNFIFO_FULL 20019) (DRV_PROC_UNKONWN_INSTRUCTION 20020)
        (DRV_ILLEGAL_OP_CODE 20021) (DRV_KINETIC_TIME_NOT_MET 20022)
        (DRV_ACCUM_TIME_NOT_MET 20023) (DRV_NO_NEW_DATA 20024)
        (DRV_PCI_DMA_FAIL 20025) (DRV_SPOOLERROR 20026)
        (DRV_SPOOLSETUPERROR 20027) (DRV_FILESIZELIMITERROR 20028)
        (DRV_ERROR_FILESAVE 20029) (DRV_TEMPERATURE_CODES 20033)
        (DRV_TEMPERATURE_OFF 20034) (DRV_TEMPERATURE_NOT_STABILIZED 20035)
        (DRV_TEMPERATURE_STABILIZED 20036) (DRV_TEMPERATURE_NOT_REACHED 20037)
        (DRV_TEMPERATURE_OUT_RANGE 20038) (DRV_TEMPERATURE_NOT_SUPPORTED 20039)
        (DRV_TEMPERATURE_DRIFT 20040) (DRV_TEMP_CODES 20033)
        (DRV_TEMP_OFF 20034) (DRV_TEMP_NOT_STABILIZED 20035)
        (DRV_TEMP_STABILIZED 20036) (DRV_TEMP_NOT_REACHED 20037)
        (DRV_TEMP_OUT_RANGE 20038) (DRV_TEMP_NOT_SUPPORTED 20039)
        (DRV_TEMP_DRIFT 20040) (DRV_GENERAL_ERRORS 20049)
        (DRV_INVALID_AUX 20050) (DRV_COF_NOTLOADED 20051) (DRV_FPGAPROG 20052)
        (DRV_FLEXERROR 20053) (DRV_GPIBERROR 20054)
        (DRV_EEPROMVERSIONERROR 20055) (DRV_DATATYPE 20064)
        (DRV_DRIVER_ERRORS 20065) (DRV_P1INVALID 20066) (DRV_P2INVALID 20067)
        (DRV_P3INVALID 20068) (DRV_P4INVALID 20069) (DRV_INIERROR 20070)
        (DRV_COFERROR 20071) (DRV_ACQUIRING 20072) (DRV_IDLE 20073)
        (DRV_TEMPCYCLE 20074) (DRV_NOT_INITIALIZED 20075) (DRV_P5INVALID 20076)
        (DRV_P6INVALID 20077) (DRV_INVALID_MODE 20078)
        (DRV_INVALID_FILTER 20079) (DRV_I2CERRORS 20080)
        (DRV_I2CDEVNOTFOUND 20081) (DRV_I2CTIMEOUT 20082) (DRV_P7INVALID 20083)
        (DRV_P8INVALID 20084) (DRV_P9INVALID 20085) (DRV_P10INVALID 20086)
        (DRV_P11INVALID 20087) (DRV_USBERROR 20089) (DRV_IOCERROR 20090)
        (DRV_VRMVERSIONERROR 20091) (DRV_USB_INTERRUPT_ENDPOINT_ERROR 20093)
        (DRV_RANDOM_TRACK_ERROR 20094) (DRV_INVALID_TRIGGER_MODE 20095)
        (DRV_LOAD_FIRMWARE_ERROR 20096) (DRV_DIVIDE_BY_ZERO_ERROR 20097)
        (DRV_INVALID_RINGEXPOSURES 20098) (DRV_BINNING_ERROR 20099)
        (DRV_INVALID_AMPLIFIER 20100) (DRV_INVALID_COUNTCONVERT_MODE 20101)
        (DRV_ERROR_NOCAMERA 20990) (DRV_NOT_SUPPORTED 20991)
        (DRV_NOT_AVAILABLE 20992) (DRV_ERROR_MAP 20115) (DRV_ERROR_UNMAP 20116)
        (DRV_ERROR_MDL 20117) (DRV_ERROR_UNMDL 20118)
        (DRV_ERROR_BUFFSIZE 20119) (DRV_ERROR_NOHANDLE 20121)
        (DRV_GATING_NOT_AVAILABLE 20130) (DRV_FPGA_VOLTAGE_ERROR 20131)
        (DRV_OW_CMD_FAIL 20150) (DRV_OWMEMORY_BAD_ADDR 20151)
        (DRV_OWCMD_NOT_AVAILABLE 20152) (DRV_OW_NO_SLAVES 20153)
        (DRV_OW_NOT_INITIALIZED 20154) (DRV_OW_ERROR_SLAVE_NUM 20155)
        (DRV_MSTIMINGS_ERROR 20156) (DRV_OA_NULL_ERROR 20173)
        (DRV_OA_PARSE_DTD_ERROR 20174) (DRV_OA_DTD_VALIDATE_ERROR 20175)
        (DRV_OA_FILE_ACCESS_ERROR 20176) (DRV_OA_FILE_DOES_NOT_EXIST 20177)
        (DRV_OA_XML_INVALID_OR_NOT_FOUND_ERROR 20178)
        (DRV_OA_PRESET_FILE_NOT_LOADED 20179)
        (DRV_OA_USER_FILE_NOT_LOADED 20180)
        (DRV_OA_PRESET_AND_USER_FILE_NOT_LOADED 20181)
        (DRV_OA_INVALID_FILE 20182) (DRV_OA_FILE_HAS_BEEN_MODIFIED 20183)
        (DRV_OA_BUFFER_FULL 20184) (DRV_OA_INVALID_STRING_LENGTH 20185)
        (DRV_OA_INVALID_CHARS_IN_NAME 20186) (DRV_OA_INVALID_NAMING 20187)
        (DRV_OA_GET_CAMERA_ERROR 20188) (DRV_OA_MODE_ALREADY_EXISTS 20189)
        (DRV_OA_STRINGS_NOT_EQUAL 20190) (DRV_OA_NO_USER_DATA 20191)
        (DRV_OA_VALUE_NOT_SUPPORTED 20192) (DRV_OA_MODE_DOES_NOT_EXIST 20193)
        (DRV_OA_CAMERA_NOT_SUPPORTED 20194) (DRV_OA_FAILED_TO_GET_MODE 20195)
        (DRV_PROCESSING_FAILED 20211)))
   (DESTRUCTURING-BIND (NAME VAL) E (SETF (GETHASH VAL *DRV-HASH*) NAME))))