(ql:quickload "split-sequence")

(defparameter *funs* 
"AbortAcquisition(void)
CancelWait(void)
CoolerOFF(void)
CoolerON(void)
DemosaicImage(WORD * grey, WORD * red, WORD * green, WORD * blue, ColorDemosaicInfo * info)
EnableKeepCleans(int iMode)
FreeInternalMemory(void)
GetAcquiredData(at_32 * arr, unsigned long size)
GetAcquiredData16(WORD * arr, unsigned long size)
GetAcquiredFloatData(float * arr, unsigned long size)
GetAcquisitionProgress(long * acc, long * series)
GetAcquisitionTimings(float * exposure, float * accumulate, float * kinetic)
GetAdjustedRingExposureTimes(int inumTimes, float * fptimes)
GetAllDMAData(at_32 * arr, unsigned long size)
GetAmpDesc(int index, char * name, int length)
GetAmpMaxSpeed(int index, float * speed)
GetAvailableCameras(long * totalCameras)
GetBackground(at_32 * arr, unsigned long size)
GetBaselineClamp(int * state)
GetBitDepth(int channel, int * depth)
GetCameraEventStatus(DWORD * camStatus)
GetCameraHandle(long cameraIndex, long * cameraHandle)
GetCameraInformation(int index, long * information)
GetCameraSerialNumber(int * number)
GetCapabilities(AndorCapabilities * caps)
GetControllerCardModel(char * controllerCardModel)
GetCountConvertWavelengthRange(float * minval, float * maxval)
GetCurrentCamera(long * cameraHandle)
GetCYMGShift(int * iXshift, int * iYShift)
GetDDGExternalOutputEnabled(at_u32 uiIndex, at_u32 * puiEnabled)
GetDDGExternalOutputPolarity(at_u32 uiIndex, at_u32 * puiPolarity)
GetDDGExternalOutputStepEnabled(at_u32 uiIndex, at_u32 * puiEnabled)
GetDDGExternalOutputTime(at_u32 uiIndex, at_u64 * puiDelay, at_u64 * puiWidth)
GetDDGGateTime(at_u64 * puiDelay, at_u64 * puiWidth)
GetDDGInsertionDelay(int * piState)
GetDDGIntelligate(int * piState)
GetDDGIOC(int * state)
GetDDGIOCFrequency(double * frequency)
GetDDGIOCNumber(unsigned long * numberPulses)
GetDDGIOCNumberRequested(at_u32 * pulses)
GetDDGIOCPeriod(at_u64 * period)
GetDDGIOCPulses(int * pulses)
GetDDGLiteGlobalControlByte(unsigned char * control)
GetDDGLiteControlByte(AT_DDGLiteChannelId channel, unsigned char * control)
GetDDGLiteInitialDelay(AT_DDGLiteChannelId channel, float * fDelay)
GetDDGLitePulseWidth(AT_DDGLiteChannelId channel, float * fWidth)
GetDDGLiteInterPulseDelay(AT_DDGLiteChannelId channel, float * fDelay)
GetDDGLitePulsesPerExposure(AT_DDGLiteChannelId channel, at_u32 * ui32Pulses)
GetDDGPulse(double wid, double resolution, double * Delay, double * Width)
GetDDGStepCoefficients(at_u32 mode, double * p1, double * p2)
GetDDGStepMode(at_u32 * mode)
GetDetector(int * xpixels, int * ypixels)
GetDICameraInfo(void * info)
GetEMCCDGain(int * gain)
GetEMGainRange(int * low, int * high)
GetExternalTriggerTermination(at_u32 * puiTermination)
GetFastestRecommendedVSSpeed(int * index, float * speed)
GetFIFOUsage(int * FIFOusage)
GetFilterMode(int * mode)
GetFKExposureTime(float * time)
GetFKVShiftSpeed(int index, int * speed)
GetFKVShiftSpeedF(int index, float * speed)
GetFrontEndStatus(int * piFlag)
GetGateMode(int * piGatemode)
GetHardwareVersion(unsigned int * PCB, unsigned int * Decode, unsigned int * dummy1, unsigned int * dummy2, unsigned int * CameraFirmwareVersion, unsigned int * CameraFirmwareBuild)
GetHeadModel(char * name)
GetHorizontalSpeed(int index, int * speed)
GetHSSpeed(int channel, int typ, int index, float * speed)
GetHVflag(int * bFlag)
GetID(int devNum, int * id)
GetImageFlip(int * iHFlip, int * iVFlip)
GetImageRotate(int * iRotate)
GetImages(long first, long last, at_32 * arr, unsigned long size, long * validfirst, long * validlast)
GetImages16(long first, long last, WORD * arr, unsigned long size, long * validfirst, long * validlast)
GetImagesPerDMA(unsigned long * images)
GetIRQ(int * IRQ)
GetKeepCleanTime(float * KeepCleanTime)
GetMaximumBinning(int ReadMode, int HorzVert, int * MaxBinning)
GetMaximumExposure(float * MaxExp)
GetMCPGain(int * piGain)
GetMCPGainRange(int * iLow, int * iHigh)
GetMCPGainTable(int iNum, int * piGain, float * pfPhotoepc)
GetMCPVoltage(int * iVoltage)
GetMinimumImageLength(int * MinImageLength)
GetMinimumNumberInSeries(int * number)
GetMostRecentColorImage16(unsigned long size, int algorithm, WORD * red, WORD * green, WORD * blue)
GetMostRecentImage(at_32 * arr, unsigned long size)
GetMostRecentImage16(WORD * arr, unsigned long size)
GetMSTimingsData(SYSTEMTIME * TimeOfStart, float * pfDifferences, int inoOfImages)
GetMetaDataInfo(SYSTEMTIME * TimeOfStart, float * pfTimeFromStart, unsigned int index)
GetMSTimingsEnabled(void)
GetNewData(at_32 * arr, unsigned long size)
GetNewData16(WORD * arr, unsigned long size)
GetNewData8(unsigned char * arr, unsigned long size)
GetNewFloatData(float * arr, unsigned long size)
GetNumberADChannels(int * channels)
GetNumberAmp(int * amp)
GetNumberAvailableImages(at_32 * first, at_32 * last)
GetNumberDDGExternalOutputs(at_u32 * puiCount)
GetNumberDevices(int * numDevs)
GetNumberFKVShiftSpeeds(int * number)
GetNumberHorizontalSpeeds(int * number)
GetNumberHSSpeeds(int channel, int typ, int * speeds)
GetNumberNewImages(long * first, long * last)
GetNumberPreAmpGains(int * noGains)
GetNumberRingExposureTimes(int * ipnumTimes)
GetNumberIO(int * iNumber)
GetNumberVerticalSpeeds(int * number)
GetNumberVSAmplitudes(int * number)
GetNumberVSSpeeds(int * speeds)
GetOldestImage(at_32 * arr, unsigned long size)
GetOldestImage16(WORD * arr, unsigned long size)
GetPhosphorStatus(int * piFlag)
GetPhysicalDMAAddress(unsigned long * Address1, unsigned long * Address2)
GetPixelSize(float * xSize, float * ySize)
GetPreAmpGain(int index, float * gain)
GetDualExposureTimes(float * exposure1, float * exposure2)
GetQE(char * sensor, float wavelength, unsigned int mode, float * QE)
GetReadOutTime(float * ReadOutTime)
GetRegisterDump(int * mode)
GetRingExposureRange(float * fpMin, float * fpMax)
GetSensitivity(int channel, int horzShift, int amplifier, int pa, float * sensitivity)
GetSizeOfCircularBuffer(long * index)
GetSlotBusDeviceFunction(DWORD * dwslot, DWORD * dwBus, DWORD * dwDevice, DWORD * dwFunction)
GetSoftwareVersion(unsigned int * eprom, unsigned int * coffile, unsigned int * vxdrev, unsigned int * vxdver, unsigned int * dllrev, unsigned int * dllver)
GetSpoolProgress(long * index)
GetStartUpTime(float * time)
GetStatus(int * status)
GetTECStatus(int * piFlag)
GetTemperature(int * temperature)
GetTemperatureF(float * temperature)
GetTemperatureRange(int * mintemp, int * maxtemp)
GetTemperatureStatus(float * SensorTemp, float * TargetTemp, float * AmbientTemp, float * CoolerVolts)
GetTotalNumberImagesAcquired(long * index)
GetIODirection(int index, int * iDirection)
GetIOLevel(int index, int * iLevel)
GetVersionInfo(AT_VersionInfoId arr, char * szVersionInfo, at_u32 ui32BufferLen)
GetVerticalSpeed(int index, int * speed)
GetVirtualDMAAddress(void ** Address1, void ** Address2)
GetVSSpeed(int index, float * speed)
GPIBReceive(int id, short address, char * text, int size)
GPIBSend(int id, short address, char * text)
I2CBurstRead(BYTE i2cAddress, long nBytes, BYTE * data)
I2CBurstWrite(BYTE i2cAddress, long nBytes, BYTE * data)
I2CRead(BYTE deviceID, BYTE intAddress, BYTE * pdata)
I2CReset(void)
I2CWrite(BYTE deviceID, BYTE intAddress, BYTE data)
IdAndorDll(void)
InAuxPort(int port, int * state)
Initialize(char * dir)
InitializeDevice(char * dir)
IsAmplifierAvailable(int iamp)
IsCoolerOn(int * iCoolerStatus)
IsCountConvertModeAvailable(int mode)
IsInternalMechanicalShutter(int * InternalShutter)
IsPreAmpGainAvailable(int channel, int amplifier, int index, int pa, int * status)
IsTriggerModeAvailable(int iTriggerMode)
Merge(const at_32 * arr, long nOrder, long nPoint, long nPixel, float * coeff, long fit, long hbin, at_32 * output, float * start, float * step_Renamed)
OutAuxPort(int port, int state)
PrepareAcquisition(void)
SaveAsBmp(char * path, char * palette, long ymin, long ymax)
SaveAsCommentedSif(char * path, char * comment)
SaveAsEDF(char * szPath, int iMode)
SaveAsFITS(char * szFileTitle, int typ)
SaveAsRaw(char * szFileTitle, int typ)
SaveAsSif(char * path)
SaveAsSPC(char * path)
SaveAsTiff(char * path, char * palette, int position, int typ)
SaveAsTiffEx(char * path, char * palette, int position, int typ, int mode)
SaveEEPROMToFile(char * cFileName)
SaveToClipBoard(char * palette)
SelectDevice(int devNum)
SendSoftwareTrigger(void)
SetAccumulationCycleTime(float time)
SetAcqStatusEvent(HANDLE statusEvent)
SetAcquisitionMode(int mode)
SetAcquisitionType(int typ)
SetADChannel(int channel)
SetAdvancedTriggerModeState(int iState)
SetBackground(at_32 * arr, unsigned long size)
SetBaselineClamp(int state)
SetBaselineOffset(int offset)
SetCameraStatusEnable(DWORD Enable)
SetComplexImage(int numAreas, int * areas)
SetCoolerMode(int mode)
SetCountConvertMode(int Mode)
SetCountConvertWavelength(float wavelength)
SetCropMode(int active, int cropHeight, int reserved)
SetCurrentCamera(long cameraHandle)
SetCustomTrackHBin(int bin)
SetDataType(int typ)
SetDACOutput(int iOption, int iResolution, int iValue)
SetDACOutputScale(int iScale)
SetDDGAddress(BYTE t0, BYTE t1, BYTE t2, BYTE t3, BYTE address)
SetDDGExternalOutputEnabled(at_u32 uiIndex, at_u32 uiEnabled)
SetDDGExternalOutputPolarity(at_u32 uiIndex, at_u32 uiPolarity)
SetDDGExternalOutputStepEnabled(at_u32 uiIndex, at_u32 uiEnabled)
SetDDGExternalOutputTime(at_u32 uiIndex, at_u64 uiDelay, at_u64 uiWidth)
SetDDGGain(int gain)
SetDDGGateStep(double step_Renamed)
SetDDGGateTime(at_u64 uiDelay, at_u64 uiWidth)
SetDDGInsertionDelay(int state)
SetDDGIntelligate(int state)
SetDDGIOC(int state)
SetDDGIOCFrequency(double frequency)
SetDDGIOCNumber(unsigned long numberPulses)
SetDDGIOCPeriod(at_u64 period)
SetDDGLiteGlobalControlByte(unsigned char control)
SetDDGLiteControlByte(AT_DDGLiteChannelId channel, unsigned char control)
SetDDGLiteInitialDelay(AT_DDGLiteChannelId channel, float fDelay)
SetDDGLitePulseWidth(AT_DDGLiteChannelId channel, float fWidth)
SetDDGLiteInterPulseDelay(AT_DDGLiteChannelId channel, float fDelay)
SetDDGLitePulsesPerExposure(AT_DDGLiteChannelId channel, at_u32 ui32Pulses)
SetDDGStepCoefficients(at_u32 mode, double p1, double p2)
SetDDGStepMode(at_u32 mode)
SetDDGTimes(double t0, double t1, double t2)
SetDDGTriggerMode(int mode)
SetDDGVariableGateStep(int mode, double p1, double p2)
SetDelayGenerator(int board, short address, int typ)
SetDMAParameters(int MaxImagesPerDMA, float SecondsPerDMA)
SetDriverEvent(HANDLE driverEvent)
SetEMAdvanced(int state)
SetEMCCDGain(int gain)
SetEMClockCompensation(int EMClockCompensationFlag)
SetEMGainMode(int mode)
SetExposureTime(float time)
SetExternalTriggerTermination(at_u32 uiTermination)
SetFanMode(int mode)
SetFastExtTrigger(int mode)
SetFastKinetics(int exposedRows, int seriesLength, float time, int mode, int hbin, int vbin)
SetFastKineticsEx(int exposedRows, int seriesLength, float time, int mode, int hbin, int vbin, int offset)
SetFilterMode(int mode)
SetFilterParameters(int width, float sensitivity, int range, float accept, int smooth, int noise)
SetFKVShiftSpeed(int index)
SetFPDP(int state)
SetFrameTransferMode(int mode)
SetFrontEndEvent(HANDLE driverEvent)
SetFullImage(int hbin, int vbin)
SetFVBHBin(int bin)
SetGain(int gain)
SetGate(float delay, float width, float stepRenamed)
SetGateMode(int gatemode)
SetHighCapacity(int state)
SetHorizontalSpeed(int index)
SetHSSpeed(int typ, int index)
SetImage(int hbin, int vbin, int hstart, int hend, int vstart, int vend)
SetImageFlip(int iHFlip, int iVFlip)
SetImageRotate(int iRotate)
SetIsolatedCropMode(int active, int cropheight, int cropwidth, int vbin, int hbin)
SetKineticCycleTime(float time)
SetMCPGain(int gain)
SetMCPGating(int gating)
SetMessageWindow(HWND wnd)
SetMetaData(int state)
SetMultiTrack(int number, int height, int offset, int * bottom, int * gap)
SetMultiTrackHBin(int bin)
SetMultiTrackHRange(int iStart, int iEnd)
SetMultiTrackScan(int trackHeight, int numberTracks, int iSIHStart, int iSIHEnd, int trackHBinning, int trackVBinning, int trackGap, int trackOffset, int trackSkip, int numberSubFrames)
SetNextAddress(at_32 * data, long lowAdd, long highAdd, long length, long physical)
SetNextAddress16(at_32 * data, long lowAdd, long highAdd, long length, long physical)
SetNumberAccumulations(int number)
SetNumberKinetics(int number)
SetNumberPrescans(int iNumber)
SetOutputAmplifier(int typ)
SetOverlapMode(int mode)
SetPCIMode(int mode, int value)
SetPhotonCounting(int state)
SetPhotonCountingThreshold(long min, long max)
SetPhosphorEvent(HANDLE driverEvent)
SetPhotonCountingDivisions(at_u32 noOfDivisions, at_32 * divisions)
SetPixelMode(int bitdepth, int colormode)
SetPreAmpGain(int index)
SetDualExposureTimes(float expTime1, float expTime2)
SetDualExposureMode(int mode)
SetRandomTracks(int numTracks, int * areas)
SetReadMode(int mode)
SetRegisterDump(int mode)
SetRingExposureTimes(int numTimes, float * times)
SetSaturationEvent(HANDLE saturationEvent)
SetShutter(int typ, int mode, int closingtime, int openingtime)
SetShutterEx(int typ, int mode, int closingtime, int openingtime, int extmode)
SetShutters(int typ, int mode, int closingtime, int openingtime, int exttype, int extmode, int dummy1, int dummy2)
SetSifComment(char * comment)
SetSingleTrack(int centre, int height)
SetSingleTrackHBin(int bin)
SetSpool(int active, int method, char * path, int framebuffersize)
SetStorageMode(long mode)
SetTECEvent(HANDLE driverEvent)
SetTemperature(int temperature)
SetTemperatureEvent(HANDLE temperatureEvent)
SetTriggerMode(int mode)
SetTriggerInvert(int mode)
GetTriggerLevelRange(float * minimum, float * maximum)
SetTriggerLevel(float f_level)
SetIODirection(int index, int iDirection)
SetIOLevel(int index, int iLevel)
SetUserEvent(HANDLE userEvent)
SetUSGenomics(long width, long height)
SetVerticalRowBuffer(int rows)
SetVerticalSpeed(int index)
SetVirtualChip(int state)
SetVSAmplitude(int index)
SetVSSpeed(int index)
ShutDown(void)
StartAcquisition(void)
UnMapPhysicalAddress(void)
WaitForAcquisition(void)
WaitForAcquisitionByHandle(long cameraHandle)
WaitForAcquisitionByHandleTimeOut(long cameraHandle, int iTimeOutMs)
WaitForAcquisitionTimeOut(int iTimeOutMs)
WhiteBalance(WORD * wRed, WORD * wGreen, WORD * wBlue, float * fRelR, float * fRelB, WhiteBalanceInfo * info)
OA_Initialize(const char * const pcFilename, unsigned int uiFileNameLen)
OA_EnableMode(const char * const pcModeName)
OA_GetModeAcqParams(const char * const pcModeName, char * const pcListOfParams)
OA_GetUserModeNames(char * pcListOfModes)
OA_GetPreSetModeNames(char * pcListOfModes)
OA_GetNumberOfUserModes(unsigned int * const puiNumberOfModes)
OA_GetNumberOfPreSetModes(unsigned int * const puiNumberOfModes)
OA_GetNumberOfAcqParams(const char * const pcModeName, unsigned int * const puiNumberOfParams)
OA_AddMode(char * pcModeName, unsigned int uiModeNameLen, char * pcModeDescription, unsigned int uiModeDescriptionLen)
OA_WriteToFile(const char * const pcFileName, unsigned int uiFileNameLen)
OA_DeleteMode(const char * const pcModeName, unsigned int uiModeNameLen)
OA_SetInt(const char * const pcModeName, const char * pcModeParam, const int iIntValue)
OA_SetFloat(const char * const pcModeName, const char * pcModeParam, const float fFloatValue)
OA_SetString(const char * const pcModeName, const char * pcModeParam, char * pcStringValue, const unsigned int uiStringLen)
OA_GetInt(const char * const pcModeName, const char * const pcModeParam, int * iIntValue)
OA_GetFloat(const char * const pcModeName, const char * const pcModeParam, float * fFloatValue)
OA_GetString(const char * const pcModeName, const char * const pcModeParam, char * pcStringValue, const unsigned int uiStringLen)
Filter_SetMode(unsigned int mode)
Filter_GetMode(unsigned int * mode)
Filter_SetThreshold(float threshold)
Filter_GetThreshold(float * threshold)
Filter_SetDataAveragingMode(int mode)
Filter_GetDataAveragingMode(int * mode)
Filter_SetAveragingFrameCount(int frames)
Filter_GetAveragingFrameCount(int * frames)
Filter_SetAveragingFactor(int averagingFactor)
Filter_GetAveragingFactor(int * averagingFactor)
PostProcessNoiseFilter(at_32 * pInputImage, at_32 * pOutputImage, int iOutputBufferSize, int iBaseline, int iMode, float fThreshold, int iHeight, int iWidth)
PostProcessCountConvert(at_32 * pInputImage, at_32 * pOutputImage, int iOutputBufferSize, int iNumImages, int iBaseline, int iMode, int iEmGain, float fQE, float fSensitivity, int iHeight, int iWidth)
unsigned int PostProcessPhotonCounting(at_32 * pInputImage, at_32 * pOutputImage, int iOutputBufferSize, int iNumImages, int iNumframes, int iNumberOfThresholds, float * pfThreshold, int iHeight, int iWidth)
unsigned int PostProcessDataAveraging(at_32 * pInputImage, at_32 * pOutputImage, int iOutputBufferSize, int iNumImages, int iAveragingFilterMode, int iHeight, int iWidth, int iFrameCount, int iAveragingFactor)
")

;; split at newlines
(defparameter *funs-split*
 (split-sequence:split-sequence #\Newline *funs*))

;; split at first (
(defparameter *funs-parm*
 (loop for l in *funs-split* collect
      (split-sequence:split-sequence #\( l)))

;; split parameterlist at ,
(defparameter *funs-parm2*
  (loop for (f parm) in *funs-parm* collect
       (list f (split-sequence:split-sequence #\, parm))))

;; remove ) at the end of parameter list
(defparameter *funs-parm3*
  (loop for (f parm) in *funs-parm2* collect
       (flet ((remove-trailing-parenthesis (ls)
		(if (= 1 (length ls))
		    nil ;; replace "void" with nil (list (first (split-sequence:SPLIT-SEQUENCE #\) (first ls))))
		    (append (butlast ls) (list (car (split-sequence:SPLIT-SEQUENCE #\) (car (last ls)))))))))
	 (list f (remove-trailing-parenthesis parm)))))

;; remove leading space at each parameter
(defparameter *funs-parm4*
  (loop for (f parms) in *funs-parm3* collect
       (list f (mapcar #'(lambda (s) (string-left-trim '(#\Space) s))  parms))))

;; split each of the parameters at space and move the last element (name) to the front
(defparameter *funs-parm5*
  (loop for (f parms) in *funs-parm4* collect
       (list f (mapcar #'(lambda (p) (let ((spli (split-sequence:SPLIT-SEQUENCE #\Space p)))
				       (list (car (last spli)) (butlast spli))))
		       parms))))

;; if the last element of the type list is "*" write sb-alien:* in front
(defparameter *funs-parm6*
  (loop for (f parms) in *funs-parm5* collect
       
       (list f
	     (mapcar #'(lambda (p) (destructuring-bind (name type) p
				     (list name 
					   (if (string= "*" (car (last type)))
					       (list 'sb-alien:* (butlast type))
					       type))))
		     parms))))



;; i want to convert the functions names to look like this:
;; GetAcquiredData16 -> get-acquired-data16
;; CoolerOFF -> cooler-off
;; GetAllDMAData -> get-all-dma-data
;; GetCYMGShift -> get-cymg-shift
;; GetDDGIOC -> get-ddgioc

;; if not at first character and character changes case from lower to
;; upper, insert hyphen

;; if not at first or second character and character changes from
;; upper to lower and there are at least 2 upper, insert hyphen before
;; current character


(defun lispify-camelcase (m)
  (let ((res nil)
	(n (length m)))
    (dotimes (i n)
      (cond 
	((and (< 0 i)
	      (lower-case-p (char m (1- i)))
	      (upper-case-p (char m i)))
	 (push #\- res)
	 (push (char m i) res))
	((and (< 1 i)
	      (upper-case-p (char m (- i 2)))
	      (upper-case-p (char m (- i 1)))
	      (lower-case-p (char m i)))
	 (pop res) ;; remove last big letter from stack
	 (push #\- res) ;; and put a hyphen in front
	 (push (char m (- i 1)) res)
	 (push (char m i) res))
	(t (push (char m i) res))))
    (string-upcase
     (make-array (length res) :element-type 'character :initial-contents (reverse res)))))

#+nil
(loop for i in '("GetAcquiredData16"
		 "CoolerOFF"
		 "GetAllDMAData"
		 "GetCYMGShift"
		 "GetDDGIOC")
     collect
     (lispify-camelcase i))

(defparameter *s*
 '("GetAcquiredData16" (("arr" (* ("WORD"))) ("size" ("unsigned" "long")))))

;; this is how it is supposed to look like:
#+nil
(sb-alien:define-alien-routine ("GetAcquiredData16" get-acquired-data16) 
    unsigned-int
  (arr (sb-alien:* word))
  (size sb-alien:unsigned-long))

(let ((bla '("1" "2")))
 (equal (car bla) "1"))

(defun string->type (ls)
  (cond 
    ((equal (car ls) '*)
     (list '* (string->type (car (cdr ls)))))
    ((equal '("WORD") ls) 'word)
    ((equal '("unsigned" "long") ls) 'unsigned-long)
	(t (error "unknown type: ~a" ls))))

(defun generate-function-definition (spec)
  (destructuring-bind (c-name params) spec
    `(sb-alien:define-alien-routine (,c-name ,(intern (lispify-camelcase c-name)))
	 ,@(loop for p in params collect
		(destructuring-bind (name type) p
		    (list (intern (string-upcase name))
			  (string->type type)))))))

#+nil
(generate-function-definition *s*)